### ISSUE TITLE
BP_DEBUG env not work for non-build step

### ISSUE THREAD

**Issue by zhoufenqin** [buildpacks/lifecycle#1006]
### Summary
I hope to see more details for build pod, so I set `BP_DEBUG=true` build env in cnbimage, but only build phase will print debug logs, other phases like `analyze`, `restore` won't print debug logs. Is it by design or how can I see debug logs in other phases?

---

##### Current behavior
debug logs not occurs in analyze container

##### Expected
debug logs should be printed in analyze container

---

##### lifecycle version
0.14.3
##### platform version(s)
kpack 0.7.2

**Comment by natalieparellano** [comment]
@zhoufenqin debug logs can be obtained by provided `-log-level debug` when invoking the lifecycle. `BP_DEBUG` is only for obtaining debug logs from a buildpack, the lifecycle component does not recognize this variable.

**Comment by natalieparellano** [comment]
I'm going to close this one as resolved, but please reach out if there are any further questions!
