### ISSUE TITLE
Generate not able to find Dockerfiles  [detector] Found '0' Dockerfiles for processing

### ISSUE THREAD

**Issue by findajay** [buildpacks/lifecycle#1071]
### Summary
I am using an extension for builder to extend run image so that I can build azure functions with paketo build pack. Here is the link to my extension. 
https://github.com/findajay/samples/tree/feature/azfunctionExtension/extensions/azfunction

Slack discussion for different issues
https://paketobuildpacks.slack.com/archives/CULAS8ACD/p1682008775698709

##### Steps

1. Update builder.toml with extensions 
2. Update group order 
3. Create builder using below command 
pack builder create localhost:5000/custom-builder \
  --config $PWD/samples/builders/paketo-base-builder/builder.toml \
  --publish
4. Build sample function app using mentioned repository, image will be produced but not run because it needs az function base image
 pack build functionapp \
  --builder localhost:5000/custom-builder \
  --network host \
  --path $PWD/samples/apps/functionapp \
  --pull-policy always \
  --verbose
5. Try running container image 
docker run functionapp -p 8080

##### Current behavior
Detection phase passed for extension 
[detector] ======== Results ========
[detector] pass: azfunction@0.0.1

But extension generate process, not able to either generate dockerfile or generated at wrong location 
[detector] Running generate for extension azfunction@0.0.1
[detector] Looking up extension
[detector] Finding plan
[detector] Invoking command
[detector] Creating plan directory
[detector] Preparing paths
[detector] Running generate command
[detector] Found '0' Dockerfiles for processing
[detector] Finished running generate for extension azfunction@0.0.1
[detector] Validating Dockerfiles
[detector] Copying Dockerfiles
[detector] Checking for new run image
[detector] Finished build, selected runImage ''

##### Expected
Extension should be added, and run image should be used from dockerfile

**Comment by findajay** [comment]
@natalieparellano

**Comment by joe-kimmel-vmw** [comment]
@findajay --  in conversation with @natalieparellano , she recommended you could try to  `ls` the contents of the output directory before exiting the ./bin/generate script to get more details of what's going on?

**Comment by findajay** [comment]
@joe-kimmel-vmw Thanks for looking into this issue. I do not get this error because I changed from sh to bash in my because of this error and with bash I was not getting this error.  So what I need to change exactly ? Do you have a repo where it is working now?

**Comment by natalieparellano** [comment]
Closing this as the original issue seems resolved, but please reach out if there are any other issues.
