### ISSUE TITLE
Upgrade api version in acceptance tests to non-deprecated version

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [buildpacks/lifecycle#1079]
### Description
Api versions 0.3 and below are officially deprecated with plans to remove support in the relatively near future. Our own acceptance tests will not be spared from this change!

currently:

```
lifecycle  $ rg "api = \"0.2\""                                                           
acceptance/testdata/restorer/container/layers/group.toml
4:  api = "0.2"

acceptance/testdata/exporter/container/layers/group.toml
4:  api = "0.2"

acceptance/testdata/analyzer/container/layers/group.toml
4:api = "0.2"

acceptance/testdata/analyzer/container/some-other-layers/group.toml
4:api = "0.2"

acceptance/testdata/builder/container/layers/different_layer_dir_from_env/group.toml
2:  api = "0.2"

acceptance/testdata/builder/container/cnb/group_tomls/always_detect_group.toml
2:  api = "0.2"

acceptance/testdata/builder/container/cnb/group_tomls/always_detect_group_buildpack2.toml
2:  api = "0.2"

acceptance/testdata/builder/container/cnb/buildpacks/hello_world/0.0.1/buildpack.toml
2:api = "0.2"

acceptance/testdata/builder/container/cnb/group_tomls/group_with_ext.toml
2:  api = "0.2"

acceptance/testdata/builder/container/cnb/buildpacks/hello_world_2/0.0.2/buildpack.toml
2:api = "0.2"

acceptance/testdata/builder/container/env_folders/different_buildpack_dir_from_env/hello_world/0.0.1/buildpack.toml
2:api = "0.2"

handlers_test.go
39:api = "0.2"
```

### Proposed solution
upgrade all relevant tests to either 0.4 or as high as they can go, moving some functionality to non-deprecated alternatives on the way. This may result in deleting certain test cases, which tested for features that are deprecated.

### Additional context
I've labeled this as "good first issue" which it ~sorta is, but also I'm lying to you:  figuring our our acceptance tests and deprecated features is a "good 100th issue" because it'll go much faster if you already know absolutely everything. But for certain kinds of new contributors this upgrade is probably a great way to learn a bunch of things about the internals of this project.

**Comment by sagnik3788** [comment]
@joe-kimmel-vmw  @natalieparellano  may I give it a try? I am new to the buildpacks community.

**Comment by natalieparellano** [comment]
@sagnik3788 we would love to have your help on this :) I will assign you the issue - please let us know if you need any help to get started.

**Comment by sagnik3788** [comment]
@natalieparellano  in this pr  #1191 and #1148 you already reomve the deprecated APIs

**Comment by natalieparellano** [comment]
@sagnik3788 thank you for your comment! I guess we can close this issue out.

Regarding the above error, I have never encountered that myself - could you check your go version? I am running go `1.21.5` and the command above works fine.

**Comment by natalieparellano** [comment]
Closing as completed in https://github.com/buildpacks/lifecycle/pull/1191 and https://github.com/buildpacks/lifecycle/pull/1148
