### ISSUE TITLE
Implementation of target env vars is misleading

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#1186]
### Summary

To provide `CNB_TARGET_*` vars in the buildpack env, the builder [concatenates](https://github.com/buildpacks/lifecycle/blob/7fda8e271f47d58b12df17a919ac8e9691f510b8/builder.go#L69) these to the lifecycle's env. This works because the `CNB_TARGET_*` vars are added to the "[allow list](https://github.com/buildpacks/lifecycle/blob/7fda8e271f47d58b12df17a919ac8e9691f510b8/env/build.go#L11-L15)" of env vars that the lifecycle will pass through to buildpacks.

However, this is misleading. Someone reading the code might think that `CNB_TARGET_*` vars need to be set in the lifecycle's env, but this is not the case (the analyzer reads this data from the run image).

We should use something like [`WithOverrides`](https://github.com/buildpacks/lifecycle/blob/7fda8e271f47d58b12df17a919ac8e9691f510b8/env/env.go#L92) to append target vars to the buildpack env in builder.go.

Note this functionality is [covered](https://github.com/buildpacks/lifecycle/blob/7fda8e271f47d58b12df17a919ac8e9691f510b8/acceptance/builder_test.go#L521-L525) by acceptance so it should be safe to refactor at the unit level.

##### lifecycle version

0.17.0+

##### platform version(s)

0.12+

**Comment by UtkarshUmre** [comment]
I'm new to this project, but I'm interested in working on this good first issue. May I give it a try?

**Comment by natalieparellano** [comment]
@UtkarshUmre we would love to have your help with this! Please let us know if there is any additional guidance we can provide that would be helpful

**Comment by sarthaksarthak9** [comment]
@UtkarshUmre r u still working on this issue?

**Comment by UtkarshUmre** [comment]
yes @sarthaksarthak9 I'm still working on this issue

**Comment by sarthaksarthak9** [comment]
> yes @sarthaksarthak9 I'm still working on this issue

ok, If u need some help .. I would love to do!!

**Comment by UtkarshUmre** [comment]
@sarthaksarthak9 thank you for offering your help. I believe I'm going to need assistance with this one. Where can I contact you?

**Comment by sarthaksarthak9** [comment]
> @sarthaksarthak9 thank you for offering your help. I believe I'm going to need assistance with this one. Where can I contact you?

you can ask your query here onwards or can dm me on slack

**Comment by edmorley** [comment]
This is currently in the lifecycle 0.20.0 milestone, however was resolved previously by #1309 which landed in lifecycle 0.19.x instead. Should the milestone be updated to 0.19.0?
