### ISSUE TITLE
Remove Support for Credential Helpers

### ISSUE THREAD

**Issue by matthewmcnew** [buildpacks/lifecycle#121]
Knative provides [Service Accounts](https://www.knative.dev/docs/build/auth/) as a mechanism to provide docker credentials to the build. 

The lifecycle should encourage users to use this workflow instead of installing and using platform specific credential helpers.

**Comment by sclevine** [comment]
I think the GCR credential helper is useful on knative+GKE so that you can avoid dealing with credentials when you're getting started.

I also think credential helper support is generally useful for supporting different authentication mechanisms on various registries.

**Comment by matthewmcnew** [comment]
I fear that it introduces a confusing interface on knative as the cnb build template behaves differently from other build templates and deviates from the knative docs. 

Credentials are already easy for new knative build users with the [ecr](https://github.com/knative/build-templates/tree/master/ecr_helper) and [gcr](https://github.com/knative/build-templates/tree/master/gcr_helper) helper scripts in the knative templates repo. 

We already support credHelpers if they are configured in the .docker/config.json if platform implementors want them.

**Comment by sclevine** [comment]
> We already support credHelpers if they are configured in the .docker/config.json if platform implementors want them.

The purpose of the cred helper support in the lifecycle is to make this easy when images are coming from different registries. The individual cred helpers don't work well together when you let them update `.docker/config.json`.

**Comment by ekcasey** [comment]
@matthewmcnew 's arguments make a lot of sense to me. If knative already has a suggested workflow and helper scripts that address this use case it's unnecessary and possibly confusing to maintain a separate implementation in lifecycle.

**Comment by sclevine** [comment]
Lets chat about this via zoom. I'm not sure we want to optimize the lifecycle just for the knative case, and I'm not convinced that knative handles this well in the multi-registry case.

**Comment by zmackie** [comment]
https://github.com/buildpacks/rfcs/pull/48 should, when implemented, address this issue

**Comment by ekcasey** [comment]
resolved by buildpacks/lifecycle#259
