### ISSUE TITLE
Handle unstable networks more robustly

### ISSUE THREAD

**Issue by scothis** [buildpacks/lifecycle#122]
I see occasional errors between the buildpack lifecycle runner and the target registry.

```
[build-step-analyze]: Error: connect to repo store 'gcr.io/<snip>': Get https://gcr.io/v2/: dial tcp: i/o timeout
```

While it would be nice if GCR was more reliable from GKE via Knative, unreliable networks are sadly common. For non-authentication related errors, perhaps the buildpack should automatically retry the operation.

**Comment by ekcasey** [comment]
@scothis I think it is the lifecycle here that needs to retry rather than the buildpack. I am in favor of making this more robust.

**Comment by ekcasey** [comment]
@scothis The library we are using to make the failing request to the registry already wraps in the transport in a `retryTransport` to guard against network flakes https://github.com/google/go-containerregistry/blob/master/pkg/v1/remote/options.go#L68

I am not sure we should add additional retries here.

**Comment by ekcasey** [comment]
@scothis This retry logic was incorporated in `lifecycle` as of the `v0.5.0` release. Feel free to reopen if you continue to see this issue with `v0.5.0` or later versions.
