### ISSUE TITLE
Make extensions not experimental for Platform 0.13 and above

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#1287]
### Summary

Image extensions are no longer experimental when using Platform 0.13.

---

### Proposal

We should remove the guards that prevent builds from proceeding unless CNB_EXPERIMENTAL_MODE is `warn` or `silent`.

---

### Related

Spec issue: https://github.com/buildpacks/spec/issues/378

---

**Comment by natalieparellano** [comment]
@loewenstein do you know anyone who would like to take this one?

**Comment by prashantrewar** [comment]
Hey @natalieparellano, I want to give a try on this issue. Could you please give me some guidance on that?

**Comment by natalieparellano** [comment]
@prashantrewar thank you, we'd love to have your help here :)

If you search for `platform.GuardExperimental(platform.FeatureDockerfiles` in the code base you'll see we do this guard in two places - once after detection (cmd/lifecycle/detector.go) and once before export (cmd/lifecycle/exporter.go). We should add something like `&& PlatformAPI.LessThan("0.13")` to the checks around these guards.

It will be slightly tricky to test this, given that Platform API 0.13 isn't considered [supported](https://github.com/buildpacks/lifecycle/blob/751c7a2737be2e6a8f66bfcc2e0cf0058661d6ff/api/apis.go#L14) yet, but maybe this is the time to add that. Then in the acceptance tests, wherever we set `CNB_EXPERIMENTAL_MODE=warn`, we can only do that for the older APIs.

LMK if you need any further guidance here!

**Comment by prashantrewar** [comment]
Hey @natalieparellano, I apologize but I did not understand what changes are you expect in the acceptance tests for `CNB_EXPERIMENTAL_MODE=warn`?

**Comment by natalieparellano** [comment]
Ah, so we where we set that env var to enable extensions ([here](https://github.com/buildpacks/lifecycle/blob/2f507d012150a4d730f0f30a10bf3bcc389bcbd4/acceptance/detector_test.go#L362), [here](https://github.com/buildpacks/lifecycle/blob/2f507d012150a4d730f0f30a10bf3bcc389bcbd4/acceptance/exporter_test.go#L148), and [here](https://github.com/buildpacks/lifecycle/blob/2f507d012150a4d730f0f30a10bf3bcc389bcbd4/acceptance/exporter_test.go#L417)) we want to do something like

```
"--env", "CNB_EXPERIMENTAL_MODE="+experimentalMode,
```

and

```
experimentalMode := "warn"
if api.MustParse(platformAPI).AtLeast("0.13") {
    experimentalMode := "error"
}
```

**Comment by prashantrewar** [comment]
Hey @natalieparellano, I created a PR for this issue, could you please take a look?

**Comment by natalieparellano** [comment]
Closed in https://github.com/buildpacks/lifecycle/pull/1295 - thank you @prashantrewar!
