### ISSUE TITLE
`CNB_TARGET_` environment variables are not set when expected

### ISSUE THREAD

**Issue by joshwlewis** [buildpacks/lifecycle#1308]
### Summary

In [Buildpack API 0.10](https://github.com/buildpacks/spec/blob/buildpack/0.10/buildpack.md?plain=1#L750-L760), it says:

> The following environment variables MUST be set by the lifecycle during the detect and build phases to describe the target runtime image, if inputs are provided.

But `lifecycle` fails to provide these `CNB_TARGET_*` environment variables if the Platform API is less than `0.12`:

https://github.com/buildpacks/lifecycle/blob/be881f29d5b4a33795e1b61bb262ce9ae439cc10/phase/analyzer.go#L84-L93

This means that a buildpack using Buildpack API 0.10 running on a platform using Platform API 0.9 won't have `CNB_TARGET_OS` and `CNB_TARGET_ARCH` set, even though these should be set according to the Buildpack API.

---

##### Steps

1. Use an older version of `pack`, like `v0.27.0`, that uses a Platform API version < 0.12
2. Run `pack build myapp --builder heroku/builder@sha256:5856c2e1f6c55ec5e289453b872f57f4ebe1a32a6da31f053cd27eddccbf21c5`
3. Observe that the build fails (some of the included buildpacks try to read `CNB_TARGET_OS`, which is not present)
4. Use a newer version of `pack` that uses Platform API version >= 0.12
5. Run `pack build myapp --builder heroku/builder@sha256:5856c2e1f6c55ec5e289453b872f57f4ebe1a32a6da31f053cd27eddccbf21c5` again.
6. Observe that the build doesn't error on missing environment variables.

##### Current behavior

Buildpacks using Buildpack API 0.10 may not receive `CNB_TARGET_OS` / `CNB_TARGET_PLATFORM` env vars when an older Platform API is in use.

##### Expected behavior

Buildpacks using Buildpack API 0.10 always receive `CNB_TARGET_OS` / `CNB_TARGET_PLATFORM` (regardless of Platform API version).

---

##### lifecycle version

`0.18.5` in my testing, but I think older versions are affected as well.

##### platform version(s)

Anything < 0.12.

**Comment by natalieparellano** [comment]
Related Slack conversation: https://cloud-native.slack.com/archives/C0333LG7C9J/p1709323194121239

We can fix this in 0.19
