### ISSUE TITLE
Lifecycle fails to build on a stack other than bionic

### ISSUE THREAD

**Issue by robdimsdale** [buildpacks/lifecycle#1355]
### Summary / Reproduction

Given:
* a buildpack with multiple stacks defined in the `buildpack.toml` **and**
* no `targets` defined in `buildpack.toml` **and**
* one of the stacks is `bionic` **and**
* we are building on a different stack (e.g. `jammy`)

Then:

The build fails with the following output:

```
            [detector] Checking for match against descriptor: {linux amd64  [{ubuntu 18.04}]}
            [detector] target distro name/version labels not found, reading /etc/os-release file
            [detector] target distro name/version labels not found, reading /etc/os-release file
            [detector] ======== Error: paketo-buildpacks/mri@1.2.3 ========
            [detector] unable to satisfy target os/arch constraints; run image: {"os":"linux","arch":"amd64"}, buildpack: [{"os":"linux","arch":"amd64","distros":[{"name":"ubuntu","version":"18.04"}]}]

```

I think this is due to [this line](https://github.com/buildpacks/lifecycle/blob/1a1de0850a2e8cd34bedccf9856886077dd702e4/buildpack/bp_descriptor.go#L71) in the lifecycle:

```
			if stack.ID == "io.buildpacks.stacks.bionic" {
				descriptor.Targets = append(descriptor.Targets, TargetMetadata{OS: "linux", Arch: "amd64", Distros: []OSDistro{{Name: "ubuntu", Version: "18.04"}}})
```

### Suggested fix

I would suggest one of the following fixes:

* remove the magic line (i.e. don't convert stacks to targets at all). This seems the most logical to me as a buildpack author, because (I think) I don't see any value in the conversion from `stacks` to `targets` during my build phase.
* check that there is exactly one stack present, and that this single stack is `bionic`. This keeps the spirit of the current behavior of converting `bionic` stack to targets, while dropping the incorrect conversion when there are multiple stacks.
* add magic lines for other commonly used stacks (e.g. `jammy`). This preserves the conversion from `stacks` to `targets` for `bionic` and other common stacks, but suffers from the question of: "which stacks do we support"?

---

##### lifecycle version

v0.19.4 and v0.19.5 - older versions are not affected

##### platform version(s)

any platform

**Comment by natalieparellano** [comment]
I think we could do 

> check that there is exactly one stack present, and that this single stack is bionic. This keeps the spirit of the current behavior of converting bionic stack to targets, while dropping the incorrect conversion when there are multiple stacks.

without any further changes to the spec. But, we will probably want to revisit this logic as we further deprecate stacks to ensure we don't hit more roadblocks like this in the future.
