### ISSUE TITLE
Exporter should invalidate the cache if it fails to write it

### ISSUE THREAD

**Issue by tomkennedy513** [buildpacks/lifecycle#1407]
### Summary
Currently, when the exporter fails to write the cache after successfully exporting the image, it emits a warning without failure. This is acceptable behavior in my opinion, but when the caching fails, the exporter should at least invalidate the cache so that we don't have a corrupted cache causing issues in subsequent builds.

---

### Proposal
The exporter should invalidate the cache whenever it fails to successfully write it, or if the cache it did write is somehow not valid.

### Context
We are seeing restore failures in kpack due to a corrupt cache after the exporter only writes out a partial cache before failing.

**Comment by jabrown85** [comment]
In the 10/17 meeting

We talked about adjusting restorer to check and fail if the cache doesn't match the metadata expected. Adding in this verification will not require a spec change unless we find performance or other issues during development of the fix.
