### ISSUE TITLE
symlink lifecycle binaries to a single binary

### ISSUE THREAD

**Issue by dgageot** [buildpacks/lifecycle#191]
Copying the six binaries of the lifecycle adds 72Mb to every builder image.

We could build a single binary instead and create symlinks for each phase of the lifecycle. It would work like busybox.

This would also make the build much faster.

wdyt?

**Comment by dgageot** [comment]
ping @sclevine @jromero

**Comment by sclevine** [comment]
Sorry for the delay. I totally support this change. Would you mind opening a short RFC for it?

**Comment by dgageot** [comment]
I saw that [this](https://github.com/buildpacks/rfcs/pull/45) was merged. Anyone working on implementing it?

**Comment by dgageot** [comment]
😛 I should have looked at the PRs first... https://github.com/buildpacks/lifecycle/pull/236

**Comment by ekcasey** [comment]
@dgageot no worries, I should have assigned myself
