### ISSUE TITLE
Handling "." in path when image is built with local implementations.

### ISSUE THREAD

**Issue by MartinForReal** [buildpacks/lifecycle#222]
When I tried to build a docker image using exporter, I found that the output image contains duplicate files. And this is because "." exists in the file path. 

```
failed to register layer: Error processing tar file(duplicates of file paths not supported): time="2020-01-02T07:31:51Z" level=info msg="SUSE:secrets :: enabled"
```

I'm using lifecycle v0.5.0 with the tekton task here https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml

And If I set -app= to a path which ends with "/"(e.g. /workspace/source/ or /workspace/source/.), the image would have duplicated dirs.

**Comment by ekcasey** [comment]
This issue appears to exist on `master` of lifecycle as well as `v0.5.0`. I am transferring the issue to the lifecycle repo.

**Comment by natalieparellano** [comment]
Accepting - see https://github.com/buildpacks/lifecycle/pull/223#issuecomment-577902411
