### ISSUE TITLE
Lifecycle should compile and package on Windows

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#234]
I should be able to run:
* `make build-windows package-windows` and get a `lifecycle-v0.5.0+windows.x86-64.tgz` with Windows executables with `.exe` suffix inside
* `make build-linux package-linux` and get a `lifecycle-v0.5.0+linux.x86-64.tgz` with Linux executables with no suffix
* `make build` and get equivalent of `build-linux` + `build-windows`
* `make package` and get equivalent of `package-linux` + `package-windows`

Output path details:
```
make build-<goos>
```
results in
```
/out
  \_<goos>/
       \_lifecycle/
          \_detector(.exe)
           ...
       \_lifecycle.toml
```
and 
```
make build-<goos> package-<goos>
```
results in
```
/out
  \_<goos>/
       \_lifecycle/
          \_detector(.exe)
           ...
       \_lifecycle.toml
   \_lifecycle-v<version>+<goos>.x86-64.tgz
```

**Comment by ekcasey** [comment]
> I should be able to run make build with GOOS=windows and see Windows executables with .exe suffix in ./out

While it's true that `make build` is aliased to `make build-linux`, If you run `make build-windows` you will get the `*.exe` files you are looking for. We could change `make build` to respect the runtime `GOOS`

> I should be able to run make package with GOOS=windows and get a lifecycle-v0.5.0+windows.x86-64.tgz with Windows executables with .exe suffix inside

`make build-windows package` will create the archive correctly. `make package` does not need the `GOOS` to be set

> Currently, layer tar files are written with paths starting from e.g., /cnb - this should be Files/cnb on Windows

While this is true of layers created by the `exporter`, it seems like it could be it's own issue, it's not related to whether the lifecycle compiles

**Comment by micahyoung** [comment]
I totally missed that `build-windows` already successfully cross-compiles. I removed that bullet point. But right now `linux` is hard-coded in the file name, regardless of `GOOS` or the contents of `out/lifecycle/*`. How would we want to support packaging options for Linux/Windows? 

Some potential examples:

`make build-windows package-windows` -> `lifecycle-v0.6.0+windows.x86-64.tgz`
or
`make build-windows package` -> `lifecycle-v0.6.0+windows.x86-64.tgz`
or
`make build-windows build-linux package` ->  (`lifecycle-v0.6.0+windows.x86-64.tgz` + `lifecycle-v0.6.0+linux.x86-64.tgz`)
or
`make build package` -> `lifecycle-v0.6.0+windows.x86-64.tgz` + `lifecycle-v0.6.0+linux.x86-64.tgz`

**Comment by ekcasey** [comment]
My hastily conjured opinions are:

we need these targets:
* `build-darwin` (for acceptance tests only)
* `build-linux`
* `build-windows`
* `build` = `build-linux` + `build-windows`
* `package-linux`
* `package-windows`
* `package` = `package-linux` + `package-windows`

One current problem is that the builds for all architectures use `out/lifecycle` as a workspace. I think we should change so that

```
make build-<goos>
```
results in
```
/out
  \_<goos>/
       \_lifecycle/
          \_detector(.exe)
           ...
       \_lifecycle.toml
```
and 
```
make build-goos package-<goos>
```
results in
```
/out
  \_<goos>/
       \_lifecycle/
          \_detector(.exe)
           ...
       \_lifecycle.toml
   \_lifecycle-v<version>+<goos>.x86-64.tgz
```

But honestly, I'm fine many variations on this, as long as it builds the right thing and is somewhat intuitive,

**Comment by micahyoung** [comment]
@ekcasey That makes lots of sense, I updated the issue.

**Comment by micahyoung** [comment]
WIP on branch `feature/234-windows-lifecycle-tarball`
