### ISSUE TITLE
exporter tries to delete app dir when all app files are sliced

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#239]
**Observed Behavior**

When all files in the application directory are included in a slice layer the exporter tries to delete the app dir itself and prints the following error message.

```
ERROR: failed to delete directory remove /workspace: device or resource busy
```

**Expected Behavior**
The `exporter` should not try to delete the app directory

**Comment by zmackie** [comment]
sliced and diced 🔪⚔️🎲
