### ISSUE TITLE
Allow caching all layers in the remote registry

### ISSUE THREAD

**Issue by burdiyan** [buildpacks/lifecycle#245]
I was assuming this behavior wrongly, so probably it's more of a feature request.

**Expected**

Layers with `cache = true` in their `<layer>.toml` to be cached in the remote registry, in addition to local volume cache. This way rebuilds with empty local cache could be faster by reusing layers from the registry.

**Current behavior**

With empty local cache, but with app being published previously, build script is rebuilding all the layers.

The reason for this is to be able to run CI jobs with ephemeral Docker daemons. If CI is close to the registry, retrieving cached layers from the registry is probably faster than rebuilding them. Maybe it could even be avoided by checking the layers metadata.

AFAIK, this is what kaniko is doing. It pushes each layer to a designated place in the registry and then before building tries to restore the cache if local cache is not present.

**Comment by simonjjones** [comment]
Hi @burdiyan we believe this feature is actually already available in lifecycle, and can be exercised by configuring the `analyzer`, `exporter` & `restorer` phases with the [`-cache-image` flag](https://github.com/buildpacks/lifecycle/blob/master/cmd/flags.go#L69).

This functionality has not, however, been enabled in pack. We'll close this issue and we can continue further discussion about enabling it on https://github.com/buildpacks/pack/issues/491

Thanks, Simon & @natalieparellano
