### ISSUE TITLE
Lifecycle Transparency: Improve log output

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#264]
Cloud Native Buildpacks are magic! Magic is great, but sometimes users want to better understand what is going on under the hood. Redesign the lifecycle output to demystify the build process for users. This will require some creativity.

**Comment by manisaiprasad** [comment]
I would like to pick this as my GSOC project. Can you help me with that? :D

**Comment by ekcasey** [comment]
Hey @manisaiprasad! We are happy you are interested in working with us. Our [slack](https://slack.buildpacks.io/) is a great place to ask questions and reach out for help with your proposal. We are usually available there to answers questions, and there is a #gsoc channel devoted to GSOC.

**Comment by ekcasey** [comment]
I am going to close this spike. Let's replace it with smaller / more actionable issues.
