### ISSUE TITLE
Analyze fails with kubernetes mounted volumes

### ISSUE THREAD

**Issue by matthewmcnew** [buildpacks/lifecycle#271]
When executing the lifecycle inside a kubernetes pod we specify the pod's `securityContext.fsgroup` to mount volumes as the CNB_USER. This will be result in the volume mounts for `/layers` and `/cache` owned by root with the group specified `fsGroup`. 

The [EnsureOwner](https://github.com/buildpacks/lifecycle/blob/master/priv/user_linux.go#L45) lifecycle check will still attempt to chown the volume mounts on these volumes because it checks both the uid and gid. This results in an error on analyze:

```
failed to chown volumes: chown /layers: operation not permitted
```

**Comment by ekcasey** [comment]
I think we can assume that, if the `gid`, is correctly, lifecycle doesn't need to fix the permissions. This shouldn't break the `pack` case when we need to chown the volumes, but should fix the permissions error you are seeing in k8s.

**Comment by matthewmcnew** [comment]
After testing #272 on minikube, it seems that not all storage classes will accurately respect the `securityContext.fsgroup`. Is it possible to just check that those directories are writeable?
