### ISSUE TITLE
exporter fails when setting the run image with CNB_RUN_IMAGE

### ISSUE THREAD

**Issue by hdp617** [buildpacks/lifecycle#274]
`exporter` is failing with `supply only one of -run-image or (deprecated) -image`
when setting the run image with `CNB_RUN_IMAGE` env var because it will set both values here https://github.com/buildpacks/lifecycle/blob/dda0b534fc1a9a88d9b8d8aef4fb9ccf3cb15916/cmd/flags.go#L104-L110.

lifecycle v0.7.1

**Comment by ekcasey** [comment]
Thanks for the bug report @hdp617. It should be a fairly easy fix (we should only set the non-depracted flag).

Getting acceptance tests in place soon should help us catch these before releasing buildpacks/lifecycle#266
