### ISSUE TITLE
Is that possible to run the buildpacks preapre and export steps as non-root?

### ISSUE THREAD

**Issue by zhangtbj** [buildpacks/lifecycle#279]
Hi all,

I am running the buildpacks buid in the shared cluster like this:
https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml#L59

But it is a shared cluster which cannot allow us to use `privileged` or `RunAsRoot` permissions.

And we don't allow the `CHOWN` capability:
which reports lots of error in build pod log:
```
chown: changing ownership of '/workspace/source/helm/nodejs/values.yaml': Operation not permitted
chown: changing ownership of '/workspace/source/helm/nodejs/Chart.yaml': Operation not permitted
chown: changing ownership of '/workspace/source/helm/nodejs/templates/imagestream.yaml': Operation not permitted
...
```

I saw the first `prepare` step is just to change the folder owner.

Is that possible to run the buildpacks `preapre` and `export` steps as non-root? Or without the `CHOWN` capability?

Thanks!

**Comment by zhangtbj** [comment]
I also took a look at other builders like kaniko or buildah, they don't require to change the `/workspace/source` folder onwership at the beginning.

**Comment by ekcasey** [comment]
I agree the `prepare` step doesn't need to be privileged and we should change that ASAP. However we do need to chown `/workspaces/source` b/c unlike the `buildah` and `kaniko` tasks the buildpacks build steps do not run as root.

- buildah runs as root & is privileged - https://github.com/tektoncd/catalog/blob/master/buildah/buildah.yaml#L43
- kaniko is not privileged but runs as root in the container - https://github.com/tektoncd/catalog/blob/master/kaniko/kaniko.yaml#L44

I was wondering if we could remove the prepare step in favor of guidance that all users add `securityContext.fsGroup` to each `TaskRun` `PodTemplate`, however when I tried this it failed presumably b/c the source is still cloned as root. It appears we need to keep chowning for now unless/until tekton provides more permission options.

**Comment by ekcasey** [comment]
Given this isn't a lifecycle bug per se, I am going to move this issue to our mirror of `tektoncd/catalog`

**Comment by ekcasey** [comment]
Looks there is some context here I was missing: https://github.com/tektoncd/catalog/pull/200

The change to make `prepare` privileged was added to make it work on openshift.

Given this isn't a lifecycle issue I am going to close this here. Please open an issue on the `tektoncd/catalog` and we can discuss there with other interested parties.

**Comment by zhangtbj** [comment]
If just requires **chown** in prepare step to change the folder owner.

It should not require the privileged permission. A `CHOWN` of defaultAddCapabilities is enough.

privileged permission is too heavy.

**Comment by ekcasey** [comment]
@zhangtbj I agree, I would like to create a PR to revert tektoncd/catalog#200. However, I do want to understand why it was contributed in the first place.

Maybe @piyush-garg can provide some context?
