### ISSUE TITLE
Ship "lifecycle image" with new versions of lifecycle 

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#285]
When we ship new versions of the lifecycle, we should also ship a "lifecycle image" that contains the minimum configuration necessary to run the `analyze`, `restore`, and `export` phases of the lifecycle.

Requirements:
* It should be based on `gcr.io/distroless/static`
* It should contain the lifecycle binaries inside `/cnb/lifecycle`
* It should contain a `/tmp` directory
* Its working directory should be `/layers`

When platforms are working with this image, they'll need to do the following (I believe):
* Provide a `stack.toml` - the default is `/cnb/stack.toml`
* Set `CNB_USER_ID` and `CNB_GROUP_ID` in the environment - **note** currently, these ids must be valid in the image because of [this check](https://github.com/buildpacks/lifecycle/blob/4e6f6de75ef4a8c183ac5f4bfa5a0f645852de0c/priv/user_linux.go#L107-L110), we should determine if this can be removed

Context:
* This would be in support of https://github.com/buildpacks/pack/issues/528
* [Slack conversation](https://buildpacks.slack.com/archives/CSFE49VGR/p1587752732046400) with further context
* [Spike](https://github.com/buildpacks/pack/issues/528#issuecomment-618045406) where various requirements were determined

Other:
* We probably want to use GitHub actions for this

**Comment by natalieparellano** [comment]
This is blocked on #286

**Comment by dfreilich** [comment]
Should this image be created using a Dockerfile, or using our Image utils?

**Comment by jromero** [comment]
I don't see how image utils is an option provided that it's a go library.

This is more of a "delivery" story in which it involves the CI/CD pipeline. In this case, very likely GitHub actions.

Some options:
- https://github.com/marketplace/actions/kaniko-builder
- https://github.com/marketplace/actions/publish-docker

**Comment by natalieparellano** [comment]
Update:

I decided to go with the publish-docker action for now. A semi-working demonstration can be found on this fork: https://github.com/natalieparellano/lifecycle/runs/664904645 (action run), https://github.com/natalieparellano/lifecycle/commit/175586af84382633338c89ca2259803475a11dde (commit)

`dive natalieparellano/lifecycle-image:0.99.9` shows that the image has the desired files and directories - however it is 89 MB in size! It appears that when doing the copy in the docker multi-stage build, the symlinks were turned into actual copies? Needs further investigation...

```
│ Layers ├──────────────────────────────────────────────────────────────────────────── ┃ ● Current Layer Contents ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cmp   Size  Command                                                                    Permission     UID:GID       Size  Filetree
    1.8 MB  FROM 513643face35501                                                       drwxr-xr-x         0:0        0 B  ├── bin
       0 B  #(nop) WORKDIR /cnb/lifecycle                                              drwxr-xr-x         0:0        0 B  ├── boot
     89 MB  #(nop) COPY multi:cd325fe6a6e031d9661e0a03b439647f10938f216bde9a1ca525a438 drwxr-xr-x         0:0      89 MB  ├── cnb
       0 B  #(nop) WORKDIR /layers                                                     drwxr-xr-x         0:0      89 MB  │   └── lifecycle
                                                                                       -rwxr-xr-x         0:0      11 MB  │       ├── analyzer  
│ Layer Details ├───────────────────────────────────────────────────────────────────── -rwxr-xr-x         0:0      11 MB  │       ├── builder
                                                                                       -rwxr-xr-x         0:0      11 MB  │       ├── creator   
Tags:   (unavailable)                                                                  -rwxr-xr-x         0:0      11 MB  │       ├── detector
Id:     dbebe985f14ad867e8cfde6dd49f9d8d063b2bdbe77f909220cdc59905e3bf4a               -rwxr-xr-x         0:0      11 MB  │       ├── exporter  
Digest: sha256:7a96df5fcadf14d71af30d279c6c12ec44b27e67632ad2cf7ba7152a2b2d2d99        -rwxr-xr-x         0:0     2.3 MB  │       ├── launcher
Command:                                                                               -rwxr-xr-x         0:0      11 MB  │       ├── lifecycle 
#(nop) WORKDIR /layers                                                                 -rwxr-xr-x         0:0      11 MB  │       ├── rebaser
                                                                                       -rwxr-xr-x         0:0      11 MB  │       └── restorer
│ Image Details ├───────────────────────────────────────────────────────────────────── drwxr-xr-x         0:0        0 B  ├── dev        
                                                                                       drwxr-xr-x         0:0     259 kB  ├─⊕ etc              
                                                                                       drwxr-xr-x 65532:65532        0 B  ├── home              
Total Image size: 90 MB                                                                drwx------ 65532:65532        0 B  │   └── nonroot      
Potential wasted space: 0 B                                                            drwxr-xr-x         0:0        0 B  ├── layers        
Image efficiency score: 100 %                                                          drwxr-xr-x         0:0        0 B  ├── lib            
                                                                                       drwxr-xr-x         0:0        0 B  ├── proc              
Count   Total Space  Path                                                              drwx------         0:0        0 B  ├── root         
                                                                                       drwxr-xr-x         0:0        0 B  ├── run          
                                                                                       drwxr-xr-x         0:0        0 B  ├── sbin        
                                                                                       drwxr-xr-x         0:0        0 B  ├── sys          
                                                                                       drwxrwxrwx         0:0        0 B  ├── tmp                            
                                                                                       drwxr-xr-x         0:0     1.5 MB  ├─⊕ usr              
                                                                                       drwxr-xr-x         0:0     1.7 kB  └─⊕ var
```

**Comment by natalieparellano** [comment]
Fixed on the branch. It was a simple change.

**Comment by natalieparellano** [comment]
In action here: https://github.com/natalieparellano/lifecycle/actions/runs/105813337

Published here: https://hub.docker.com/repository/docker/natalieparellano/lifecycle-image

Working with pack here: https://github.com/buildpacks/pack/pull/631/checks?check_run_id=679067785
