### ISSUE TITLE
Feature Request: Add Timestamps to the Logs

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/lifecycle#293]
It would be helpful to see timestamps in actions, to diagnose what time each stage takes, in order to tune the overall build time.

**Comment by jromero** [comment]
This PR might be related: https://github.com/buildpacks/lifecycle/pull/97

My 2 cents: I don't believe it should be the lifecycle's responsibility to print out timestamps. That should be a higher level concern. In this case, the platforms such as [pack](https://github.com/buildpacks/pack/blob/0501b34a9be65832f2b8a60cbcffbb4d1342b333/cmd/pack/main.go#L54), [Jenkins](https://www.jenkins.io/doc/pipeline/steps/timestamper/). 

It would be different if lifecycle would tell me it `took X seconds building application`. I'd like a summary.

Ideally, using additional tools would provide a much better experience such as https://github.com/paypal/gnomon:

 [![asciicast](https://asciinema.org/a/iYlMSq2sGZJvz0hgJ7DJOlmxK.svg)](https://asciinema.org/a/iYlMSq2sGZJvz0hgJ7DJOlmxK)

**Comment by dfreilich** [comment]
Should I close the issue, then, or move it to Pack? Alternatively, if we decide that it would be best to go with third party tools, perhaps we can explicitly call that out in the Readme/docs

**Comment by matthewmcnew** [comment]
Requiring the platform to provide the timestamps would exclude platforms that execute the lifecycle directly. 
Looping in @doddatpivotal who originally provided this feedback.

**Comment by jromero** [comment]
@dfreilich,

I don't think so, it's worth having the conversation since the historic PR/issue don't have too much detail.

@matthewmcnew,

Are we thinking about any specific platform? FWIW, k8s appears to have this feature built-in: https://kubectl.docs.kubernetes.io/pages/container_debugging/container_logs.html

> Include timestamps in the log lines
> 
> $ kubectl logs -l app=echo --timestamps
> 
> 2018-11-16T05:26:31.38898405Z hello
> 2018-11-16T05:27:13.363932497Z hello

**Comment by ekcasey** [comment]
@dfreilich `pack` already has a `--timestamps` flag, but it seems kinda broken
```
> pack --help
...
Global Flags:
      --no-color     Disable color output
  -q, --quiet        Show less output
      --timestamps   Enable timestamps in output
  -v, --verbose      Show more output
```

```
>pack build   <image> --timestamps
base-cnb: Pulling from paketo-buildpacks/run
Digest: sha256:15bccd9803f63b20a38a6834821a74d9c3949eb475cf759446047dc9586ca2a9
Status: Image is up to date for gcr.io/paketo-buildpacks/run:base-cnb
2020/05/14 16:35:56.818382 ===> DETECTING
[detector] 6 of 15 buildpacks participating
[detector] paketo-buildpacks/bellsoft-liberica 2.4.1
[detector] paketo-buildpacks/maven             1.3.0-2-g867ee37
[detector] paketo-buildpacks/executable-jar    1.2.2
[detector] paketo-buildpacks/apache-tomcat     1.1.2
[detector] paketo-buildpacks/dist-zip          1.2.2
[detector] paketo-buildpacks/spring-boot       1.5.2
2020/05/14 16:35:58.759832 ===> ANALYZING
...
```

**Comment by natalieparellano** [comment]
Now that pack is using the creator it is even more broken :/

**Comment by yaelharel** [comment]
It looks like a bug in `pack`. Do you think we should close this issue and open a bug in `pack` instead?

**Comment by ekcasey** [comment]
@yaelharel I agree, I think this is a `pack` bug unless somebody wants to step in and make a case for timestamps in lifecycle.

**Comment by ekcasey** [comment]
closing in favor of https://github.com/buildpacks/pack/issues/668
