### ISSUE TITLE
Confusing error message when creator is given an invalid image reference

### ISSUE THREAD

**Issue by scottfrederick** [buildpacks/lifecycle#295]
### Summary

When the `creator` is given an image name that it can't parse, a somewhat confusing error message is returned to the builder client. 

##### Steps

This issue can't be re-created with `pack` because `pack` doesn't currently use the `creator` and it parses the image reference itself before passing to the lifecycle anyway. 

It can be re-created with a trivial Spring Boot application using either the Maven plugin with [`mvn spring-boot:build-image`](https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/maven-plugin/reference/html/#build-image) or the Gradle plugin with [`gradle bootBuildImage`](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/gradle-plugin/reference/html/#build-image). Providing an image name that contains upper-case characters will cause an image reference parsing error. 

* Create a project using [Spring Initializr](https://start.spring.io/), selecting Maven, Spring Boot 2.3.0, and the name `DemoProject`
* Build an image from the project with `mvn spring-boot:build-image -Dspring-boot.build-image.imageName=docker.io/library/DemoProject:1.0` 

##### Current behavior
The example above results in an error like this when the Spring Boot Maven plugin invokes `creator`: 

```
[INFO]  > Running creator
[INFO]     [creator]     ERROR: failed to all tags must have the same registry as the exported image: could not parse reference: docker.io/library/DemoProject:1.0
```

The `failed to all tags must...` part has strange phrasing, and the `all tags must have the same registry as the exported image` part is somewhat confusing in the context of trying to create an image. Beyond that, it is not obvious why the reference could not be parsed. 

##### Expected behavior

An error message that more concisely indicates that the image reference can't be parsed would be an improvement. An indication of what part of the image reference isn't acceptable would be better.

**Comment by ekcasey** [comment]
@scottfrederick I agree we should fix that error message. After some experimentation I think `ggcr` is failing to parse the image reference because it doesn't like the capital letters in the tag. We could lowercase the user inputs before using them but, fwiw, `docker tag` etc. also chokes on capital letters (albeit with a better error message).
