### ISSUE TITLE
Environment variables set in windows profile scripts are not set in the process environment

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#359]
On the Linux side, we have an "outer bash" and an "inner bash" to accomplish this. On Windows, this is complicated by the fact that `cmd` does not accept a `.bat` script from stdin - it needs to be written to a file.

Possible way forward - we write a temporary file and pass that to `cmd`. This would introduce file i/o and potentially slow down the launch process, but may be the "correct" thing to do.

Are there other options? This may require investigation.

**Comment by natalieparellano** [comment]
cc @micahyoung @ameyer-pivotal ^^ thoughts?
