### ISSUE TITLE
exporter errors when process type is not present

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#376]
### Summary

A change to the exporter has made it to where it incorrectly [errors when a process type is not present and `--process-type` is provided](https://github.com/buildpacks/lifecycle/blob/f65216e2ad4692027fb64649fb1187a1b502e8be/exporter_test.go#L1030-L1036). Additionally, the `lifecycle` will no longer default to a `web` process type when multiple process types are present.

This currently causes a gnarly issue for `pack` when a build process sets multiple process types (including `web`) in that the final app image is not runnable without passing an entrypoint. Given that `pack` can't hint at the `lifecycle` as to which process type to make default if multiple are present makes the UX poor and non-backwards compatible to the previous functionality.

---

### Expectation

Based on the RFC, this should [warn and set the process type to launcher](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md#exporter).

> Currently, it is possible to set the default process-type to a non-existent process-type. This will no longer be allowed. If the default process does not exist, the `exporter` will warn and set the entrypoint to `/cnb/lifecycle/launcher`.

---

##### lifecycle version

v0.9.0

##### platform version(s)

0.4

##### anything else?

[Slack discussion](https://buildpacks.slack.com/archives/CSFE49VGR/p1597211416214800)

**Comment by natalieparellano** [comment]
It looks like trying to set the default process to a non-existent type always failed: https://github.com/buildpacks/lifecycle/blob/9dd3dbcefa7c332790270986cd83d455bd60cf04/exporter_test.go#L831-L837

**Comment by natalieparellano** [comment]
This would bring us in line with the spec:

> If <process-type> does not match a buildpack-provided process:
If there is exactly one buildpack-provided process:
MUST have ENTRYPOINT=/cnb/process/<type> where <type> matches the type of the process
Else:
MUST have ENTRYPOINT set to /cnb/lifecycle/launcher
