### ISSUE TITLE
Exporter: when no default process is specified, don't set a default process (even when there is only one process)

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#378]
With platform API 0.4, when no default process is specified and there is exactly one process, the exporter will set the default process (entrypoint) to the only process.

As discussed in WG: the lifecycle should be as transparent as possible and have no opinions. The current behavior could be surprising to some users.

Given: a build with only one process type using platform API 0.4
When: no process type is specified (`-process-type` not passed)
Then: the exporter should set the entrypoint to `/cnb/lifecycle/launcher` (or the Windows equivalent)

**Comment by natalieparellano** [comment]
On further inspection, this would require spec changes.

**Comment by ekcasey** [comment]
I am onboard with this spec change if folks think it makes the platform API easier to understand

**Comment by natalieparellano** [comment]
Blocked on https://github.com/buildpacks/spec/pull/137

**Comment by ekcasey** [comment]
Closing and merging with https://github.com/buildpacks/lifecycle/issues/457 based on the outcome of [RFC 0064](https://github.com/buildpacks/rfcs/blob/main/text/0064-buildpacks-contribute-default-process-type.md).
