### ISSUE TITLE
Lifecycle release process should be documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#382]
Maybe while we're at it, we could explore using GitHub Actions instead of Concourse.

Here is the current flow (to the extent that I understand it):

#### Regular release:

In code:
* Update VERSION file <- actually Concourse overrides the version [here](https://github.com/buildpacks/ci/blob/e1c848918343f36a453b4a15d8e751bf78b037c3/tasks/build-lifecycle/run#L18-L19) so not sure why this is necessary other than keeping GHA artifacts in sync
* Update lifecycle.toml file

In Concourse:
* wait for lifecycle-build to pass
* trigger lifecycle-release manually

In GitHub:
* update release notes and make it "live"

#### IF it's a patch release and there have been merges to main since the release was cut:

In code:
* create a release branch release/my.patch.version
* Update lifecycle.toml file

In Concourse:
* use lifecycle-patch pipeline <- not currently checked in to the buildpacks/ci repo, but modifiable with `fly`

We should write this down somewhere so that anyone on the team could ship if they need to.

**Comment by ekcasey** [comment]
I agree that this should be documented and soon. I would like to move the concourse portion of the process to GHA first (now that manually triggered actions are supported).
