### ISSUE TITLE
PATH breaks when env var gets added to app image

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#385]
### Summary

@nebhale found and reported via [slack](https://buildpacks.slack.com/archives/CSFE49VGR/p1597352031301300) that the final app image fails to find the process when an additional env var is provided to `docker run`.

---

##### Steps

1. Generate an app image with Lifecycle using Platform API 0.4
2. Run image with `--env`
```
docker run -it -p 8080:8080 --entrypoint web --env ALPHA="bravo" applications/jar        
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"web\": executable file not found in $PATH": unknown.
```

##### Expected

---

##### lifecycle version

0.9.0

##### platform version(s)

0.4

##### anything else?

Looking at the docker inspect of the produced image yields:

```
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CNB_LAYERS_DIR=/layers",
                "CNB_APP_DIR=/workspace",
                "CNB_PLATFORM_API=0.4",
                "CNB_DEPRECATION_MODE=quiet",
                "PATH=/cnb/process:/cnb/lifecycle:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```

**Comment by jabrown85** [comment]
The duplicate `Env` values of `PATH` in this example, I think, are pushing us into undefined territory.

>These strings have the form name=value; names shall not contain the character '='. For values to be portable across systems conforming to POSIX.1-2017, the value shall be composed of characters from the portable character set (except NUL and as indicated below). There is no meaning associated with the order of strings in the environment. If more than one string in an environment of a process has the same name, the consequences are undefined.

OCI runtime spec: https://github.com/opencontainers/runtime-spec/blob/278a7d747c17521625b723ac1361d006ba4a3bb4/config.md
Referenced env spec: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_01
