### ISSUE TITLE
0.9.1 version of the lifecycle identifies api version as 0.2

### ISSUE THREAD

**Issue by listaction** [buildpacks/lifecycle#388]
### Summary
In many dependent repos where lifecycle 0.9.1 is used , build breaks and flags 0.9.1 as using api version 0.2.  My guess is that the back-compatibility section is being used as the main version. 

##### Steps
```
git clone https://github.com/projectriff/builder.git
cd builder 
make
```
ERROR: validating buildpacks: buildpack paketo-buildpacks/leiningen@1.0.0 (Buildpack API version 0.4) is incompatible with lifecycle 0.9.1 (Buildpack API version 0.2)
..
ERROR: validating buildpacks: buildpack projectriff/java-function@0.7.0 (Buildpack API version 0.4) is incompatible with lifecycle 0.9.0 (Buildpack API version 0.2)
make: *** [build] Error 1
```

##### Last known working version 
```
git checkout 6a7894e2889bd763350a9d667f32e62f01f64175
make 
succeeds as it uses 0.87 of the lifecycle 
```
any help resolving this for dependent projects that break is super appreciated!

---

### Context

##### lifecycle version
0.9.1 breaks many things here 
https://github.com/projectriff/builder/blob/main/builder.toml#L4-L11
cc: @nebhale 

p.s. I am trying to use cloud functions with project riff, and see that 0.7.0 of the java invoker is needed for any of the java functions to work as 0.6.0, 0.5.0 generate "mapper is null" error when the function is invoked.

**Comment by ekcasey** [comment]
Hey @listaction, the validation error is being thrown by `pack`. The current release of `pack` is still using the backwards-compatibility section of `lifecycle.toml` and therefore doesn't know that lifecycle `v0.9.1` supports buildpack API `0.4`. This should be resolved in the upcoming release of pack https://github.com/buildpacks/pack/issues/780 (expected this week).

**Comment by listaction** [comment]
that's kind of what I was guessing , but I am new to cf / buildpacks -
appreciate the response and look forward to it.

**Comment by ekcasey** [comment]
Because this is a `pack` issue that is currently being tracked here (https://github.com/buildpacks/pack/issues/780) I am going to close this lifecycle issue. Feel free to reopen if you have further comments/questions.
