### ISSUE TITLE
Change defaults that depend on the working dir

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#393]
https://github.com/buildpacks/spec/pull/128

In platform API 0.5, all default file paths that are currently relative to the working directory should changed to be relative to the layers directory.

**Comment by yaelharel** [comment]
The default paths that should be changed are:
```
- group.toml
- plan.toml
- analyzed.toml
- project-metadata.toml
- report.toml
```

**Comment by yaelharel** [comment]
@ekcasey, does the default directory supposed to be `layers` or should it be based on the configured layers directory?
For example - if the layers directory was configured to `/abc`, should the `group.toml` still be set to `/layers/group.toml` or should it be `/abc/group.toml`?

**Comment by ekcasey** [comment]
@yaelharel It should be based on the configured layers directory.
