### ISSUE TITLE
[RFC 0052] Opt-in Layer Caching

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#395]
[RFC 0052](https://github.com/buildpacks/rfcs/blob/main/text/0052-opt-in-layer-caching.md)
https://github.com/buildpacks/rfcs/pull/99
https://github.com/buildpacks/spec/issues/132

For buildpacks with API >= 0.5 require buildpacks to explicitly indicate intent to reuse layers as describe in the RFC.

For buildpack with API < 0.5, keep the existing behavior.

**Comment by natalieparellano** [comment]
RFC to update layer TOML: https://github.com/buildpacks/rfcs/pull/132
