### ISSUE TITLE
Update Windows lifecycle image base

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/lifecycle#421]
According to the [nanoserver dockerhub page](https://hub.docker.com/_/microsoft-windows-nanoserver#:~:text=Lifecycle%20Notices), Nano Server 1809 will EOL on Nov. 10th, 2020. For this reason, the tooling that generates the Windows lifecycle image should be updated to use Server Core LTSC 2019 instead, which [won't EOL until 2024](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle#:~:text=01%2F09%2F2024).

Concretely, in the lifecycle image generator tooling, change `mcr.microsoft.com/windows/nanoserver:1809` to `mcr.microsoft.com/windows/servercore:ltsc2019`.

**Comment by micahyoung** [comment]
FWIW, it's unlinkely 1809 will disappear anytime soon, if the older images are any indication:
```
```
