### ISSUE TITLE
Support Node-identity-based authentication

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#426]
Use `ggcr` `k8schain` package to provide workload identity based authentication in the lifecycle. The keychain returned by [NewNoClient](`https://godoc.org/github.com/google/go-containerregistry/pkg/authn/k8schain#NewNoClient) should allow us to provide credential-helper-like authentication when the lifecycle runs in-cluster on a public cloud provider without requiring that cred-helper executables are actually installed on the image.

**Comment by natalieparellano** [comment]
Does this have implications for the work described here? https://github.com/buildpacks/lifecycle/issues/339#issuecomment-685110074

**Comment by ekcasey** [comment]
@natalieparellano Assuming we made the changes described in #339, I think we would want to add this additional keychain to the end of our `MultiKeychain`.

**Comment by natalieparellano** [comment]
kubelet image credential provider docs: https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/

**Comment by natalieparellano** [comment]
Blocked on https://github.com/kubernetes/kubernetes/issues/86245

**Comment by natalieparellano** [comment]
The linked issue is still open, but we can at least add an `amazonKeychain` and `azureKeychain` to our [`MultiKeychain`](https://github.com/buildpacks/lifecycle/blob/86d84b37ee3a261453fc5675da8a84c5a7f5dda5/auth/env_keychain.go#L27) to help users of those platforms.

**Comment by natalieparellano** [comment]
Didn't mean to close this
