### ISSUE TITLE
Report `failed to exec as user 1000:1000: operation not permitted` error at restore step when use lifecycle 0.9.2 release to build source code 

### ISSUE THREAD

**Issue by xiujuan95** [buildpacks/lifecycle#451]
### Summary

When I use the latest (0.9.2) `lifecycle` to build my source code, at `restore` step, it showed me below error:
```
ERROR: failed to exec as user 1000:1000: operation not permitted
```
BTW, if I switched to lifecycle `0.9.1` release, there was no any issue.

And if I use `0.9.2` and build image in a no PSP (`pod security policy`) environment, also no problem. I am building my source code based on tekton-pipeline, and my environment has a pod security policy restriction about tekton-pipeline pod:
```
kubectl get psp
tekton-restricted-psp           false   CHOWN,DAC_OVERRIDE,FOWNER,SETGID,SETUID,SETFCAP                                                                       RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```

So not sure if `0.9.2` had some security changes? I went through the difference between `0.9.1` and `0.9.2`: https://github.com/buildpacks/lifecycle/compare/v0.9.1...v0.9.2. I didn't find any meaningful changes. 

Could you pls help me about this issue? Thanks in advance!

---

### Reproduction

Create tekton task use this sample: https://github.com/tektoncd/catalog/blob/master/task/buildpacks-phases/0.1/buildpacks-phases.yaml (change lifecyle form 0.8.1 to 0.9.2)

##### Expected

---

##### lifecycle version

0.9.2

##### anything else?

tekton-pipeline version is 0.14.2

**Comment by natalieparellano** [comment]
Summarizing from Slack - it looks like the error is with the Tekton task itself, vs. the lifecycle. What is surfacing in lifecycle 0.9.2 is actually a [bugfix](https://github.com/buildpacks/lifecycle/pull/433/files#diff-92c6ed289675df1e2edf598694dfc99f22a591496c130d10a43e86830cbd3686R121), such that failure to drop privileges actually throws an error.

Fix for the Tekton task is to add the following to the steps that use the lifecycle image:
```
securityContext:
    runAsUser: $(params.USER_ID)
    runAsGroup: $(params.GROUP_ID)
```

We plan to update the Tekton task to include the security context.
