### ISSUE TITLE
Exporter always tries to delete cache image

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/lifecycle#453]
### Summary
When using the `-cache-image` flag, the `exporter` always issues a delete to the registry.

---

##### Steps

1. Run a `registry:2` service ephemerally to ensure no images exist via `docker run -it -p 5000:5000 registry:2`
2. Run `/cnb/lifecycle/creator repo/img` with `-cache-image=localhost:5000/repo/img:build-cache` using the local registry as the target registry.
3. Observe that lifecycle sends a `DELETE` for the "previous" cache image, when there could not have been one.

##### Current behavior

Lifecycle logs
```
Adding 1/1 app layer(s)
Adding layer 'launcher'
Adding layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
*** Images (sha256:62a0edeb85a97bd975367e9e9b57d75c2ae8b1af3b7c477080b4f4b48ac489f7):
      192.168.86.34:5000/frozen-woodland-11119/function
Adding cache layer 'heroku/go:shim'
Unable to delete previous cache image: DELETE http://192.168.86.34:5000/v2/frozen-woodland-11119/function/manifests/sha256:03cbce912ef1a8a658f73c660ab9c539d67188622f00b15c4f15b89b884f0e10: UNSUPPORTED: The operation is unsupported.complete
```
Registry logs
```
ERRO[0261] response completed with error                 err.code=unsupported err.message="The operation is unsupported." go.version=go1.11.2 http.request.host="192.168.86.34:5000" http.request.id=f030c486-e117-4125-8af3-1542da211d04 http.request.method=DELETE http.request.remoteaddr="172.17.0.1:43940" http.request.uri="/v2/frozen-woodland-11119/function/manifests/sha256:03cbce912ef1a8a658f73c660ab9c539d67188622f00b15c4f15b89b884f0e10" http.request.useragent=go-containerregistry http.response.contenttype="application/json; charset=utf-8" http.response.duration="926.028µs" http.response.status=405 http.response.written=78 vars.name="frozen-woodland-11119/function" vars.reference="sha256:03cbce912ef1a8a658f73c660ab9c539d67188622f00b15c4f15b89b884f0e10"
172.17.0.1 - - [23/Oct/2020:17:19:42 +0000] "DELETE /v2/frozen-woodland-11119/function/manifests/sha256:03cbce912ef1a8a658f73c660ab9c539d67188622f00b15c4f15b89b884f0e10 HTTP/1.1" 405 78 "" "go-containerregistry"
```

##### Expected

I expected lifecycle to know the remote cache image does not yet exist and not send the `DELETE` or log an error about it not existing.

Kind of an aside: Is there a way to detect if a registry supports `DELETE` at all? I see, by default, the `registry:2` does not enable delete. It would be even better if lifecycle could know the remote registry would never be OK with the delete and skip that step entirely.

---

##### lifecycle version

`0.9.1`

**Comment by dwillist** [comment]
Ya running into this issue as well when attempting to implement https://github.com/buildpacks/pack/issues/491

**Comment by jabrown85** [comment]
I did a bit of research on this. We can solve the error on first `DELETE` by inspecting the image we are about to try and delete. I've got some outstanding questions on how best to implement that, but I've got it working using `CreatedAt`. It just isn't possible to test with the current `imgutil` `FakeImage`

For subsequent delete operations on images that _do_ exist, I don't think there is any way to detect what features a registry has enabled. I see a couple paths forward we could take.

1. Always send the delete, only log if the error is not `UNSUPPORTED: The operation is unsupported`/`405`
2. Add a way to never send deletes. `--cache-image-delete=false` or `CACHE_IMG_DELETE=false` so exporter never deletes caches. This could be useful for platforms where there is only ever a single target registry that is known to not support deletes or the registry is responsible for cleaning up unreferenced blobs.
3. Add a way for platform operators to supply a configuration per registry host on this. Sort of like `CNB_REGISTRY_AUTH`. 3.

**Comment by dwillist** [comment]
Interesting, also did a bit of poking around in this & might be missing something here think this is solved by checking if `origImage` exists before commiting, then delete it only if it existed? (From the [Commit](https://github.com/buildpacks/lifecycle/blob/0e19f4bb9528ae0bcf501584883b477585ded724/cache/image_cache.go#L93) function)

I think `DELETE`s are being issued because `oldImage` & `newImage` just happen to refer to the same image as seen [here](https://github.com/buildpacks/lifecycle/blob/0e19f4bb9528ae0bcf501584883b477585ded724/cache/image_cache.go#L25)

It seems like the `UNSUPPORTED` is a particularly poor choice of  return status as manifest deletion is a [requirement of v2 registries](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#deleting-manifests) and on subsequent pushes of the same image `DELETE` is used and works correctly.

**Comment by jabrown85** [comment]
Yup, you are right on the bug. We were just discussing the error in slack on checking existence before writing to the tag. Working up the fix for it now

**Comment by dwillist** [comment]
haha whoops, ya posted then noticed you had it figured out then deleted the post.
