### ISSUE TITLE
Slices No Longer Handle Trailing Slashes Properly

### ISSUE THREAD

**Issue by nebhale** [buildpacks/lifecycle#455]
### Summary
Previously, the Spring Boot Layer Index was properly interpreted and created layers with metadata that had trailing slashes in the paths.  The [recent change](https://github.com/buildpacks/lifecycle/commit/23f1c9745a042cd4c9434512a157400514fdc20e) to stop using `filepath.Glob` has broken this (new matching algorithm).  Credit to @lzimd for [diagnosing](https://github.com/paketo-buildpacks/spring-boot/issues/1#issuecomment-719908485) this issue.

---

### Reproduction
Reproduction can be accomplished with @jonashackt's [repository](https://github.com/jonashackt/spring-boot-buildpack).

#### Steps
1. `git clone https://github.com/jonashackt/spring-boot-buildpack`
2. `mvn spring-boot:build-image`
3. `dive docker.io/library/spring-boot-buildpack:0.0.1-SNAPSHOT`

**Comment by nebhale** [comment]
Found in https://github.com/paketo-buildpacks/spring-boot/issues/1

**Comment by ekcasey** [comment]
Resolved by #456
