### ISSUE TITLE
[RFC 0066] Experimental Features

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#460]
[RFC 0066](https://github.com/buildpacks/rfcs/blob/main/text/0066-lifecycle-prelease-version-and-experimental-section.md)
buildpacks/rfcs#115
buildpacks/spec#141

Setup framework to handle experimental modes.

**Comment by natalieparellano** [comment]
Closed in https://github.com/buildpacks/lifecycle/pull/860
