### ISSUE TITLE
[Builder] Acceptance Tests

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#466]
Add acceptances tests for [builder](https://github.com/buildpacks/spec/blob/main/platform.md#builder).

**Comment by natalieparellano** [comment]
The tests should run on Linux and Windows. They should cover most command invocations (see Detector & Analyzer as examples) and should include a test of the exit code in case of error (see Detector as an example).

**Comment by natalieparellano** [comment]
In particular the tests related to user permissions will be very valuable for stackpacks.

**Comment by haliliceylan** [comment]
I would like to pick this up !
