### ISSUE TITLE
README.md Platform API is out of date

### ISSUE THREAD

**Issue by briandealwis** [buildpacks/lifecycle#474]
### Summary

The README.md API support section is out of date.
https://github.com/buildpacks/lifecycle/blob/fd943ff40cf3afc6baffce5edb1887b1de9943b9/README.md#L8-L10

It might be more useful to instead have a table of lifecycle versions with supported Platform and Buildpacks API versions.

**Comment by ekcasey** [comment]
@briandealwis thanks for bringing this to our attention!
