### ISSUE TITLE
Publish to dockerhub 504 errors

### ISSUE THREAD

**Issue by dwillist** [buildpacks/lifecycle#497]
### Summary

On some computers with slower ( < 15Mbps upload speed) exporting an image with large (> 100Mbs) layers to dockerhub fails with a `504 Gateway timeout` error.

After digging into this its difficult to see how network speed would help resolve this problem at the `http` or application level. Though it could have effects further down the network stack that I don't understand.

---

### Reproduction
Way I've been able to reliably reproduce this is using`pack` and the `java/maven` sample app from `github.com/paketo-buildpacks/samples`. Then using the `paketobuildpacks/builder:base` builder. 

Running a `pack build <image-repo>/<image-name> -p ./java/maven --publish --builder paketobuildpacks/builder:base` can result in reproducible error.

##### Current behavior
A 504 Error is returned. 

##### Expected
Image to be successfully pushed. This workflow works perfectly for other registries such as `gcr`.

#### Other info:
Strangely the following work perfectly fine:
1) Follow the above reproduction steps to push an image to `gcr.io`
2) pull the image from gcr
3) push the image back to dockerhub using `crane` or `docker push`.

---

##### lifecycle version
`0.10.1`, but effects all versions >= `0.9.1` (haven't tested lower than this)

##### platform version(s)
current pack main branch: https://github.com/buildpacks/pack/tree/3d165d5e203e3980701d39e6466ee3874a9c6c40

### Logs:
[504.log](https://github.com/buildpacks/lifecycle/files/5780416/504.log)

**Comment by natalieparellano** [comment]
Related Slack conversation: https://buildpacks.slack.com/archives/CSFE49VGR/p1609950080221800

**Comment by dwillist** [comment]
So I think I can explain what is happening here. The problem has pieces from a couple different repositories and I'm not sure the correct fix is a change to this one, but its where the problem starts.

Given the following:
1) `remote` images from `imgutil` stream their `tar.gz` layer files, this way they are never stored in memory. In fact the `gzip` compression is recalculated every time we read one of these files. See the [`LayerFromFile` function](https://github.com/buildpacks/imgutil/blob/2f6fbe7a8bf327b996fcad4b88e68e2862e62b19/remote/remote.go#L414) And the `gzip` compression is calculated on demand (when `Read` is called).
2) If data is highly compressible many of the `Read(p []byte) ...` calls on this reader are expensive (it needs to do the compression) and return a tiny number of bytes (I'm getting < 480 bytes on most reads).
3) When saving a layer in a remote image we use only a single `PATCH` request ( from [ggcr](https://github.com/google/go-containerregistry/blob/b4c870f4ff6fdec76f9ef7d222b60e99db902865/pkg/v1/remote/write.go#L266))
4) All reads to our layer pass through a `io.Pipe` object which is unbuffered and every `Write` requires a matching `Read`. [io.Pipe is initialized here](https://github.com/google/go-containerregistry/blob/b4c870f4ff6fdec76f9ef7d222b60e99db902865/pkg/v1/internal/gzip/zip.go#L39)

As a result the `PATCH` request used to upload a layer is `chunked`(for large layers) with a bunch of tiny chunks. The overhead of sending all of these small packets dooms large highly compressible layers on slower networks.

**Comment by dwillist** [comment]
Here are some logs that if builds where we buffer data out of the `io.Pipe`. One buffers at least 256 bytes, the other at least 65526 bytes. (Note the reads may still be less than the amount of data in the buffer)


[single-layer-65526-upload.log](https://github.com/buildpacks/lifecycle/files/5803965/single-layer-buf-upload.log)
[single-layer-256-buf-upload.log](https://github.com/buildpacks/lifecycle/files/5803966/single-layer-small-buf-upload.log)

**Comment by dwillist** [comment]
Possible fixes:
(1) assuming that we can gzip compress files faster than we can send pieces of a chunked request (seems pretty reasonable) Might want to look into using something other than an `io.Pipe` (this would be a change in `ggcr`)
(2) we add some sort of buffering when reading a layer blob (basically what I did to write the above logs) (also a change in `ggcr`)
(3) We add the [`tarball.WithCachedCompression`](https://github.com/google/go-containerregistry/blob/b4c870f4ff6fdec76f9ef7d222b60e99db902865/pkg/v1/tarball/layer.go#L102) option when [adding a layer to an image](https://github.com/buildpacks/imgutil/blob/2f6fbe7a8bf327b996fcad4b88e68e2862e62b19/remote/remote.go#L415), this would save us some time as we currently compress layers at least 2 times. Once when calculating the digest, and once when writing the image. But will require additional memory allocation to store the cache (worst case everything is random data and we get no compression :( ). (This is an `imgutil` change)

Might be others, but wondering if any of the above sound reasonable

**Comment by dwillist** [comment]
GGCR bug opened [here](google/go-containerregistry#920)

**Comment by dwillist** [comment]
This error is fixed in ggcr by [this PR](https://github.com/google/go-containerregistry/pull/923) seems like as soon as there is another release we should be able to pull it in.

**Comment by dwillist** [comment]
@jabrown85 yep!
