### ISSUE TITLE
[RFC 0073] Add Support for Asset Cache artifacts

### ISSUE THREAD

**Issue by dwillist** [buildpacks/lifecycle#521]
### Description
[RFC 0073](https://github.com/buildpacks/rfcs/blob/main/text/0073-offline-buildpackages.md)
[buildpacks/rfcs#121](https://github.com/dwillist/rfcs/blob/offline-buildpackages/text/0000-offline-buildpackages.md)
buildpacks/spec#184

Implement the following features in order to satisfy the requirements in RFC 0073. This issue will link out to others that implement the features outlined below.
- add support for `CNB_ASSETS` env var to access assets provided by asset-cache

**Comment by natalieparellano** [comment]
Would stack buildpacks be able to use asset caches?

**Comment by dwillist** [comment]
Yep, they assets will appear as layers on the ephemeral builder image.

**Comment by natalieparellano** [comment]
Resolved by https://github.com/buildpacks/lifecycle/pull/591
