### ISSUE TITLE
[RFC 0074] Move layer types to new table in layer.toml

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#522]
[RFC 0074](https://github.com/buildpacks/rfcs/blob/main/text/0074-layer-table.md)
https://github.com/buildpacks/rfcs/pull/132

https://github.com/buildpacks/spec/issues/185

**Comment by natalieparellano** [comment]
Goes hand-in-hand with https://github.com/buildpacks/lifecycle/issues/395

**Comment by yaelharel** [comment]
#537 was merged. Closing this issue.
