### ISSUE TITLE
Windows Cache Images are Linux Images

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/lifecycle#529]
### Summary

Pack allows users to create cache images. When creating a cache image from a WCOW machine, I would expect those cache images to themselves be WCOW images, but they are instead linux containers. 

> When creating a new cache image, I think this gets called… so the cache will default to Linux even if running on Windows

https://github.com/buildpacks/imgutil/blob/30601e371ce385a990992de9ed9ff7b373f7c524/remote/remote.go#L108

---

##### Steps

1. run `pack build --publish --cache-image` 
2. `docker pull` the cache image
3. attempt to `docker inspect` the cache image

##### Current behavior

It failed to pull the image, because it's a linux image. 

##### Expected

It would pull the windows image

---

### Context
It happened in this run: https://github.com/buildpacks/pack/runs/1919007343

##### lifecycle version

Lifecycle 0.10.2

##### platform version(s)

Pack 0.17.0

**Comment by natalieparellano** [comment]
Adding this for discussion as there are maybe a couple of ways we could solve this.

**Comment by natalieparellano** [comment]
Resolved by #532
