### ISSUE TITLE
[RFC 0075] Move analyze phase before detect

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#530]
[RFC 0075](https://github.com/buildpacks/rfcs/blob/main/text/0075-move-analyze-phase.md)
buildpacks/rfcs#135
https://github.com/buildpacks/spec/issues/194

Make analysis the first phase in the build operation and require that the lifecycle validate run-image stack and mixins.

**Comment by natalieparellano** [comment]
Blocked on https://github.com/buildpacks/spec/pull/197

**Comment by natalieparellano** [comment]
Resolved by #582
