### ISSUE TITLE
Release process should run pack acceptance tests with pre-release lifecycle configured

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#542]
Blocked on https://github.com/buildpacks/pack/issues/1105

When there are new commits to a release branch and/or when the "draft-release" action is run, we should run the pack acceptance tests with the pre-release artifact configured. This should be done on Linux and Windows.

**Comment by natalieparellano** [comment]
Note that this is somewhat of a stop-gap before we have more robust acceptance test coverage. But it would at least remove a manual step that is currently being done.

**Comment by yaelharel** [comment]
I think we should update the [release doc](https://github.com/buildpacks/lifecycle/blob/main/RELEASE.md) as part of this issue.

**Comment by natalieparellano** [comment]
> I think we should update the release doc

Made some changes in https://github.com/buildpacks/lifecycle/pull/665

**Comment by natalieparellano** [comment]
Resolved by https://github.com/buildpacks/lifecycle/pull/652 and #665
