### ISSUE TITLE
Bill of Materials Should Include Buildpack ID and Version

### ISSUE THREAD

**Issue by nebhale** [buildpacks/lifecycle#55]
Currently the Bill of Materials in `config/metadata.toml` contains metadata about items contributed by the buildpacks and claimed by each at the end of the `build` phase.  The bill of materials (or another related section in `config/metadata.toml` should _additionally_ contain an explicit listing of the buildpack ID and version used to stage the application as querying against this information can be useful as well.

**Comment by ekcasey** [comment]
It appears this was implemented as part of the contractual build plan (#149)

```
pack inspect-image node --bom | jq .local
[
  {
    "name": "node",
    "version": "12.14.1",
    "metadata": {
      "licenses": [],
      "name": "Node Engine",
      "sha256": "cc7914edc7ead576de2502e15f7ad31f451b19e12846a6999467d0c9471d8799",
      "stacks": [
        "io.buildpacks.stacks.bionic"
      ],
      "uri": "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.14.1-bionic-cc7914ed.tgz"
    },
    "buildpack": {
      "id": "org.cloudfoundry.node-engine",
      "version": "0.0.146"
    }
  }
]
```
