### ISSUE TITLE
[RFC 0081] Process Specific Working Directories

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#557]
[RFC 0081](https://github.com/buildpacks/rfcs/blob/main/text/0081-process-specific-working-directory.md)
https://github.com/buildpacks/rfcs/pull/144/files

**Comment by natalieparellano** [comment]
Marking this as ready, but we may want to keep an eye on the conversation around https://github.com/buildpacks/rfcs/pull/148 as it could also lead to changes in the launcher.

**Comment by mboldt** [comment]
Per https://github.com/buildpacks/spec/milestone/19 should we update the label to api/buildpack/0.8 ?
