### ISSUE TITLE
Spring boot 2.3.4 docker build in Google Cloud build fails when using lifecycle V0.11.0

### ISSUE THREAD

**Issue by gtstewar** [buildpacks/lifecycle#558]
### Summary
As of yesterday, lifecycle V0.10.2 was being used in the Google Cloud Run build to compile a Spring Boot V2.3.4 / maven project and package it into a docker image to be deployed on Google cloud. All builds were working as expected. As of this morning, V0.11.0 is being used for these builds with no changes to our dependencies file and the builds are stalling out. Also, I rolled the code back to the state of a previously successful build and attempted to build now and it failed while using lifecycle V0.11.0

##### Steps

1. Attempt to build a Spring boot / maven project with command "mvn clean -T 1C spring-boot:build-image -DskipTests"

##### Current behavior
> Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 6%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 13%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 21%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 34%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 46%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 52%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 61%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 100%
[INFO]  > Pulled builder image 'gcr.io/paketo-buildpacks/builder@sha256:4c2adb842fc513a9eb469a5cd962085e6b27d5c4878d361527ed4d24c69b3d7b'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:base-cnb' 34%
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:base-cnb' 100%
[INFO]  > Pulled run image 'paketobuildpacks/run@sha256:0bf521429c5fac06616ef542da735f9e34c4997cc5d5987242eb7199b04ac923'
[INFO]  > Executing lifecycle version v0.11.0
[INFO]  > Using build cache volume 'pack-cache-fc9c264d1178.build'
[INFO] 
[INFO]  > Running creator

^That's as far as it gets. It sits on this command until the build times out

##### Expected

 Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 9%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 14%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 19%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 24%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 35%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 43%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 53%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 61%
[INFO]  > Pulling builder image 'gcr.io/paketo-buildpacks/builder:base-platform-api-0.3' 100%
[INFO]  > Pulled builder image 'gcr.io/paketo-buildpacks/builder@sha256:d9297e4f4f00a2ed318735f84c8ab964d71e86020e24304b9989a63f482735a2'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:base-cnb' 100%
[INFO]  > Pulled run image 'paketobuildpacks/run@sha256:0bf521429c5fac06616ef542da735f9e34c4997cc5d5987242eb7199b04ac923'
[INFO]  > Executing lifecycle version v0.10.2
[INFO]  > Using build cache volume 'pack-cache-fc9c264d1178.build'
[INFO] 
[INFO]  > Running creator
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     5 of 18 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/ca-certificates   2.1.0
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 7.1.0
[INFO]     [creator]     paketo-buildpacks/executable-jar    5.0.0
[INFO]     [creator]     paketo-buildpacks/dist-zip          4.0.0
[INFO]     [creator]     paketo-buildpacks/spring-boot       4.1.0
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Previous image with name "us.gcr.io/dev-mvp/bitbucket_cfurlon_anduin/art-engine:7e1ee4af6ebd11e808468c703784cf9ac23315de" not found
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]     
[INFO]     [creator]     Paketo CA Certificates Buildpack 2.1.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-c

^The build continues after hitting Running Creator
---

##### lifecycle version
V0.11.0

**Comment by furlongce** [comment]
I'm running into this too

**Comment by natalieparellano** [comment]
Thanks for reporting this. We're looking into this and it appears to be a cross between https://github.com/buildpacks/lifecycle/pull/544 and https://github.com/kubernetes/kubernetes/issues/86245. We're working on cutting a patch soon.

**Comment by natalieparellano** [comment]
@gtstewar @furlongce this should be patched in https://github.com/buildpacks/lifecycle/releases/tag/v0.11.1. Could you let us know if it resolves the issue?

**Comment by gtstewar** [comment]
@natalieparellano Yes, I will let you know. Thanks!

**Comment by gtstewar** [comment]
@natalieparellano The build was successful but it went back to using V0.10.2 so I’m not sure if that’s what you were intending to happen

**Comment by ekcasey** [comment]
hey @gtstewar the paketo builders rolled back to v0.10.2 temporarily but have now pulled in v0.11.1 which should resolve the issue.

**Comment by natalieparellano** [comment]
@gtstewar @furlongce any update on this?

**Comment by gtstewar** [comment]
@natalieparellano Builds are now using v0.11.1 and are completing successfully. Thank you!

**Comment by natalieparellano** [comment]
@gtstewar Awesome! Thanks for the update!

Closing this as resolved in https://github.com/buildpacks/lifecycle/pull/560.
