### ISSUE TITLE
[Build] Remove excluded paths

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/lifecycle#564]
[RFC](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md)

After all stackpacks have executed, after cache snapshots have been made and before elevated permissions are dropped - Delete all paths matching the `[[excludes]]` of each [`stack-layer.toml`](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md#stack-layertoml-toml).

**Comment by natalieparellano** [comment]
Blocked on https://github.com/buildpacks/lifecycle/issues/567
