### ISSUE TITLE
[Extend] Capture launch snapshot

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/lifecycle#569]
[RFC](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md)

Given a [`stack-layer.toml`](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md#stack-layertoml-toml) like below, `extender` will produce a snapshot and optionally a cache snapshot.

```
cat << EOF > $1/stack-layer.toml
[[excludes]]
paths = [ "/var/cache" ]
cache = true
EOF
```

In the example above, the `/var/cache` would end up in the cache snapshot and any other filesystem changes will be in the launch snapshot.

**Comment by natalieparellano** [comment]
Could we describe how the `<layer>.toml` would get created? Looking at https://github.com/buildpacks/lifecycle/pull/410/files#r501277302 (I assume `extend` also needs to produce this file).

**Comment by natalieparellano** [comment]
IIUC there are actually three slices of files - launch, excluded and cached, and simply excluded. E.g., 

```
cat << EOF > $1/stack-layer.toml
[[excludes]]
paths = [ "/excluded/and/cached" ]
cache = true
[[excludes]]
paths = [ "/just/excluded" ]
cache = false
EOF
```

**Comment by natalieparellano** [comment]
Blocked on https://github.com/buildpacks/lifecycle/issues/568
