### ISSUE TITLE
[Rebase] Execute stackpacks

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/lifecycle#570]
[RFC](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md)

Rebase, running on the new `run-image` will execute stackpacks defined in a `stack-group.toml`. The build plan will come from the previous image, stored in a label or via `-plan`.  Using `<stack-platform>` instead of the application platform directory.

The `rebaser` will need to validate it is on the run-image and that it has the stackpacks.

Q: Does rebase need to do any additional validation around mixins?
Q: Where does `stack-group.toml` come from? I realize it is an input, but I don't know how a platform would have that from a build that occurred many days/months ago.
Q: Same with `plan`. The spec changes mention `-plan` but the main text only mentions it being stored in a label on the app image.

**Comment by natalieparellano** [comment]
(from RFC) Q: During a rebase, if the new run image statically includes a mixin that was previously provided by a stack buildpack, should the providing stack buildpack rerun?
