### ISSUE TITLE
[Detect] Detect on stackpacks

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/lifecycle#576]
Goal: The lifecycle will compare the list of required mixins to the list of mixins provided by stack and stack buildpacks in accordance with stage-specific mixin rules. If any mixins are still not provided, the build will fail.

To accomplish this, the list of run-time and build-time mixins that are already present in the run image and build image must be provided to the detector in `analyzed.toml`.

If a stack buildpack provides (only) a mixin that is already installed on the stack, there is no reason for it to run. Also, we need to update the detect code to be smart enough to successfully resolve a build plan were `requires` are met by the stack.

A stack buildpack may only write non-mixin `provides` into the build plan. If a stack buildpack attempts to write `requires` or mixin `provides` into the build plan, detect should fail.

During the detect phase, the lifecycle will create two build plans and `stack-group.toml`.

* Build plans:
One will be used as an input for the `build` phase and the other will be used as an input for the `extend` phase.
  * If a mixin is required for "run" stage only, it will not appear in the buildpack plan entries during build.
  * If a mixin is required for "build" stage only, it will not appear in the buildpack plan entries during extend.

  The entries of the buildpack plan during the build and extend phases will have a new mixin key. For example:

```
[[entries]]
mixin = "libpq"
```

* Stack-group:
Similar to `group.toml` but for the detected stack buildpack group for the run image.

**Comment by natalieparellano** [comment]
> To accomplish this, the list of run-time and build-time mixins that are already present in the run image and build image must be provided to the detector.

Note that this is coming from `analyzed.toml`.

> During the detect phase, the lifecycle will create two build plans

This requires knowing a bit about how the detector is operating, but I **think** what will happen is that we'll try to resolve a single build plan (verify that all "requires" are met by "provides") and then filter that plan into two parts. 

> The RFC discuss build plans and then write about buildpack plans. Is it an error?

I think this makes sense. I think the filtering mentioned above also applies to the buildpack plans.

Suppose stackpack-A provides build:some-mixin and run:some-mixin. During the build phase, its buildpack plan will only include build:some-mixin. And during the extend phase, its buildpack plan will only include run:some-mixin.

**Comment by natalieparellano** [comment]
> The lifecycle will compare the list of required mixins to the list of mixins provided by stack and stack buildpacks in accordance with stage-specific mixin rules.

Note that mixins provided by the stack are coming from stack.toml and mixins provided by stack buildpacks are coming from each stack buildpacks' buildpack.toml. Thus mixins are only satisfied statically. Stack buildpacks cannot provide mixins in the build plan.

However stack buildpacks CAN provide non-mixins in the build plan. Thus stack buildpacks should still run even if all mixins are already satisfied on the stack.

**Comment by natalieparellano** [comment]
Blocked on solidifying the changes to analyzed.toml.
