### ISSUE TITLE
[Restore] Download cached stackpack layers

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/lifecycle#577]
The lifecycle will download the excluded cached stackpack layers with the cache and store them as tarballs in the `<layers>` directory and the `<run-layers>` directory.
Note: The restorer won't extract the layers because it doesn't run with root privileges.

**Comment by natalieparellano** [comment]
> The lifecycle will download the excluded cached stackpack layers with the cache and store them as tarballs in the <layers> directory and the <run-layers> directory.

Maybe it's worth calling out that stackpack layers in the `<layers>` directory are `build = true` layers that are intended to change the filesystem of the build environment. (Thus they require root privileges to extract.)

I would think that stackpack layers in the `<run-layers>` directory would never need to be extracted. 

Maybe this is obvious but we should also restore the `<layer>.toml` files to the appropriate directory.
