### ISSUE TITLE
[Restore] Acceptance tests should run for every api + be added to

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#601]
### Description
Currently they only run for `CNB_PLATFORM_API=0.3`. We should turn them into a table test and have them run for every platform api. We should selectively skip tests that don't apply to a certain api.

We should also add tests that are relevant for the reversal of analyze & detect.

**Comment by natalieparellano** [comment]
This MAY be covered by additions to #582

**Comment by natalieparellano** [comment]
@jabrown85 should we close this one?

**Comment by jabrown85** [comment]
Yeah, I think we are good here!
