### ISSUE TITLE
Keychain should be more robust in handling registry URLs

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#608]
### Summary
We've observed anecdotally when running our Tekton task template that if you configure your secret like this: `https://index.docker.io/v1` (note the absence of trailing slash), you MAY get `UNAUTHORIZED: authentication required` failures in pushing to Docker Hub. Configuring the secret with `https://index.docker.io/v1/` seems to work.

We may need to do some "cleaning" of the registry URL in order for ggcr to be able to correctly parse it.

##### lifecycle version
At least 0.10.0.

May be related to https://github.com/buildpacks/docs/issues/361.

Since we're doing https://github.com/buildpacks/lifecycle/issues/572, we might consider looking at this at the same time.

**Comment by natalieparellano** [comment]
After looking into this a bit further, I'm not sure there is anything we could do here without changes upstream. The key that is used to look up the auth in ggcr is hard-coded with a trailing slash: https://github.com/google/go-containerregistry/blob/a58f1d55bc799c55deb7cfaa35ef5234e9da7ff3/pkg/authn/keychain.go#L55

This is done for historical reasons and I'm not sure I follow the full context, but it's worth noting that docker also uses a trailing slash: https://github.com/moby/moby/blob/fc01c2b481097a6057bec3cd1ab2d7b4488c50c4/registry/config.go#L39

**Comment by jonjohnsonjr** [comment]
How does `docker` handle `https://index.docker.io/v1`?

**Comment by natalieparellano** [comment]
Experimenting with the cli, `https://index.docker.io/v1` becomes `index.docker.io` in the config file, and tells me `Login Succeeded` - but I'm not able to push images with those credentials. I'll dig in a bit more to see what the code path is and where this gets dropped - but I guess the short answer is that it's not handled very well!

**Comment by natalieparellano** [comment]
Labeling this as "wontfix" for now as I believe this is something we'd need to change outside of the lifecycle. If anyone disagrees, feel free to comment / re-open.
