### ISSUE TITLE
Lifecycle unnecessarily re-pulls image manifest

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#613]
### Summary
There is a bug in imgutil: https://github.com/buildpacks/imgutil/blob/77564c120f1445ad6c9c0ca3dfd8de99be016279/remote/remote.go#L209 (should be a `break` after this line) where we unnecessarily re-pull the image manifest when there is no error.

This results in an additional 300ms of latency for each pull and also triples the number of pull requests that count toward the [download rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) if the image is on Docker Hub.

We'll need to bump the version of imgutil to a version that has a fix for this issue.

Thanks @jjbustamante for catching this.

**Comment by ekcasey** [comment]
Resolved in #614
