### ISSUE TITLE
[RFC 0087] Add BOM to Layer Content Metadata

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#623]
[RFC 0087](https://github.com/buildpacks/rfcs/blob/main/text/0087-bom-in-layer-metadata.md)
https://github.com/buildpacks/rfcs/pull/151
https://github.com/buildpacks/spec/issues/227

Allow buildpacks to contribute BOM entries for a specific layer in the associated `layer.toml` file.

**Comment by natalieparellano** [comment]
Let's block this pending the outcome of https://github.com/buildpacks/rfcs/pull/166

**Comment by natalieparellano** [comment]
Superseded by RFC 0095
