### ISSUE TITLE
CNB_ASSETS var should be present in detect env

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#649]
See https://github.com/buildpacks/spec/pull/229#discussion_r661715338

This contradicts the implementation: https://github.com/buildpacks/lifecycle/blob/771ac0b9d0d56cd3baaf28355498a0a636ea6182/acceptance/detector_test.go#L139

We could change the linked test to expect the `CNB_ASSETS` variable.

**Comment by aemengo** [comment]
@natalieparellano I'd like to work on this! _Put me in coach!_
