### ISSUE TITLE
Detect should print buildpack output when parsing plan failed

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#663]
### Summary
If the lifecycle fails to parse the plan output by a buildpack, we return an error but we do not set the output: https://github.com/buildpacks/lifecycle/blob/3297dacad3f0d58bcbbb44dff0d896b9ad1c28c1/buildpack/detect.go#L79-L90 (notice that we don’t set `Output: out.Bytes()` on line 89). This makes debugging difficult. We should set the output if parsing the plan fails.

---

##### Steps

1. Run detect on a buildpack with a `bin/detect` that succeeds, but outputs an invalid plan.toml
2. Observe that buildpack output is not printed (even with verbose logging)

**Comment by yaelharel** [comment]
The bug was reported [here](https://buildpacks.slack.com/archives/C94UJCNV6/p1626448959306300).
