### ISSUE TITLE
Lifecycle images should be signed

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#671]
### Description
We should sign images published to buildpacksio/lifecycle. Probably with cosign. This should be accomplished in GitHub actions.

**Comment by natalieparellano** [comment]
We'd need to publish a public key somewhere. Cosign attaches it to each release: https://github.com/sigstore/cosign/releases

**Comment by natalieparellano** [comment]
This is made slightly more complicated by the fact that we publish images with each new commit to main and/or the release branch, and release after.

**Comment by dlorenc** [comment]
Let me know if we can help at all here! I'm a maintainer on the cosign project, and have spent some time recently thinking through how to sign automated workflows like this.

**Comment by yaelharel** [comment]
Hi @dlorenc! Thank you for reaching out!
We would love to get your advice on a solution for this issue.
@natalieparellano started to work on [this PR](https://github.com/buildpacks/lifecycle/pull/683#issuecomment-886222499).
It would be great if you can take a look and write your feedback.
Anyway, @natalieparellano will reach out to you when she's back from her vacation.
Thanks again 😊

**Comment by natalieparellano** [comment]
@dlorenc I would love to chat with you! What's the best way to get in touch?
