### ISSUE TITLE
Run lifecycle units on ARM architecture

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#672]
### Description
We should run our unit tests on arm architecture in GitHub actions.

This will help us verify if the lifecycle when running on arm exports an arm image.

**Comment by natalieparellano** [comment]
We should do this before we "release" ARM binaries for the lifecycle. (cc @imjasonh )

**Comment by imjasonh** [comment]
Unfortunately GHA doesn't support arm runners unless you run them yourself. Travis CI supports arm hosted runners but... Travis.

**Comment by natalieparellano** [comment]
I want to say that the CNB project may be able to procure resources for this 🤞🏼 let me check!

**Comment by natalieparellano** [comment]
Resolved by #699
