### ISSUE TITLE
Verify lifecycle 0.12.0-rc.1 with Tekton

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#681]
### Description
Typically, we use the pack acceptance tests to verify that a lifecycle build using all 5 phases will work end-to-end. This inevitably won't cover the latest platform api version as pack won't support that api until the lifecycle does.

With platform 0.7, we are reversing the order of analyze & detect, a larger change from the platform's perspective. We should verify that builds on platform 0.7 work end-to-end by exercising a couple builds in Tekton. This was done prior to merging https://github.com/buildpacks/lifecycle/pull/582 but there have been changes to the `cmd` package since then that would be good to verify.

### Desired Outcome
Tekton taskruns that use both the 5 phases and the creator, and platform api 0.7. 

Blocked on https://github.com/buildpacks/lifecycle/pull/662 for now.

**Comment by aemengo** [comment]
@yaelharel Thanks for taking the lead on this and for such a clear write-up. I was able to follow through with your instructions and validate the following on my tekton environment:

- creator taskrun
    - [x] platform 0.7
    - [x] `RUN_IMAGE` param
- phases taskrun
    - [x] platform 0.7
    - [x] reverse analyze & detect 
    - [x] analyzer w/ `-run-image` flag
    - [x] analyzer w/ `-stack` flag
    - [x] exporter w/o `-run-image` flag

@natalieparellano I know these kinds of things feel a little more valid when you inspect them yourself. I still have my tekton environment up, if you'd like to take a look. To see if I didn't skip any exercise steps 😉

**Comment by natalieparellano** [comment]
@yaelharel @aemengo thanks for the great work on this!
