### ISSUE TITLE
Draft release workflow ambiguous in choosing linux artifact

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#682]
### Summary
Currently, we're just looking for a workflow with "linux" in the name (see [here](https://github.com/buildpacks/lifecycle/blob/8f801a55fd4a1c9ee12eadd0b1c5b5cbf5ed98b5/.github/workflows/draft-release.yml#L75)). But now that we're shipping linux artifacts for amd64 and arm64, this is ambiguous.

May be fixed by https://github.com/buildpacks/lifecycle/pull/680

**Comment by yaelharel** [comment]
Fixed as part of https://github.com/buildpacks/lifecycle/pull/679.
