### ISSUE TITLE
Need for opened connection to root owned unix socket

### ISSUE THREAD

**Issue by matejvasek** [buildpacks/lifecycle#686]
### Summary
When building with trusted builder the builder container runs as root only at the beginning. Then it delevates access rights before running phases. This means the builder container is not able to dial the unix docker socket owned by root. Right now this is solved by dialing the socket at the startup while still running as a root. Then the connection needs to be opened for the whole duration of build. This is problem if the daemon auto-close inactive connection (`podman` does that after 20 seconds).

The builder should be able to redial the socket at any time.

Ideas for solution:
1. Run the `analyze`, `restore` and `export` as a root and run only the `detect` and `build` as non-root (via `exec`)
2. Exec designated process at startup (with uid=0) which would proxy communication to the unix socket.
3. Keep pining the daemon in order to avoid auto-close of inactive connection.
4. Somehow (don't know exactly how) map the container user to be in the `docker` group.

##### Steps

1. create simple Java app: `mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DgroupId=com.example -DartifactId=test-bp -B`
2. in one terminal run podman as a service: `podman system service unix:///tmp/podman.sock --time=0 --log-level=debug`
3. in another terminal set docker socket via envvar: `export DOCKER_HOST="unix:///tmp/podman.sock"` and then try to build the app: `pack build test-bp --builder paketobuildpacks/builder:full --docker-host=inherit --trust-builder=true --pull-policy=if-not-present -v`

##### Current behavior

The build fails:

```
ERROR: failed to  image: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info": EOF
ERROR: failed to build: executing lifecycle: failed with status code: 1
```
You can also noticed following in the podman's log:

```
DEBU[0045] IdleTracker 0xc000590010:closed 3m+1h/4t connection(s) 
DEBU[0045] IdleTracker 0xc0000111f0:closed 2m+1h/4t connection(s) 
```

##### Expected
Build proceeds without error.

**Comment by matejvasek** [comment]
related https://github.com/buildpacks/lifecycle/pull/684

**Comment by matejvasek** [comment]
cc @ekcasey @aemengo

**Comment by matejvasek** [comment]
@natalieparellano It works now with `podman`. Still this should be fixed in `pack` there is nothing wrong with closing a socket after prolonged inactivity.

**Comment by natalieparellano** [comment]
Thanks @matejvasek . Should we close https://github.com/buildpacks/lifecycle/pull/684 then? (With the understanding that the root issue will go away eventually when we get rid of exporting to the daemon?)

**Comment by natalieparellano** [comment]
Closing this issue as `podman` now works and we intend for the daemon to go away eventually.

**Comment by matejvasek** [comment]
@natalieparellano we might need to re-open this, the issue is present if user uses systemd to start the daemon with default configuration.

**Comment by matejvasek** [comment]
@natalieparellano are there any proposals how to fix this?

**Comment by natalieparellano** [comment]
Closed in https://github.com/buildpacks/lifecycle/pull/684
