### ISSUE TITLE
Update post-release action when cosign v1.2.0 is released

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#702]
### Description
#701 signs the SBOM after attaching it. cosign v1.2.0 will sign the attached SBOM when the image is signed. We can update the post-release action to use this flow when cosign v1.2.0 is released.

Example usage:
```
cosign sign <image> --attachment=sbom
```

Milestone:
https://github.com/sigstore/cosign/milestone/9

**Comment by samj1912** [comment]
This should be closed?

**Comment by natalieparellano** [comment]
Fixed in 0.12.0
