### ISSUE TITLE
Spike: performance impact of "read only layers"

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#703]
### Description
See comment: https://github.com/buildpacks/rfcs/pull/155#issuecomment-888548761

We would like to understand the performance impact of the proposal in order to inform the RFC discussion.

**Comment by mboldt** [comment]
I can dive in to this.

**Comment by mboldt** [comment]
I've done an initial experiment and captured it here: https://github.com/mboldt/lifecycle-703-read-only-layers

In short, hashing the layers directories after each buildpack runs doubled the (cached) build time for spring-petclinic-rest with the paketo buildpacks. This seems unacceptable.

More details in the experiment repo.

I propose giving a file system watcher a try as an alternate approach, to see if that might be less costly.

**Comment by mboldt** [comment]
Implemented the file system watcher, and it is much more efficient. I've updated my [experiment repo](https://github.com/mboldt/lifecycle-703-read-only-layers) with this approach and the results.

I think this shows a performant approach to detect violation of the buildpack spec where two buildpacks modify the same layer, and therefore can close out this issue/spike.

**Comment by natalieparellano** [comment]
Amazing work @mboldt ! https://github.com/buildpacks/rfcs/pull/155 has all the context for anyone looking to continue the conversation.
