### ISSUE TITLE
Spike: Lifecycle should run hooks’ bin/build

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#714]
Broken out from #709 

#### (4) Lifecycle should run hooks’ bin/build
Hooks may be executed in parallel
For each hook:
* `<layers>` is replaced by `<output>`
* If a hook is missing bin/build, the hook root should be treated as a pre-populated <output> directory
* Output files should be validated:
  * build.toml:
    * May include args table
  * launch.toml:
    * May include args table
    * Must not include processes or slices

#### (5) Lifecycle should provide Dockerfiles output by hooks to subsequent phases
The files should probably be copied to a volume (/layers? Does this depend on https://github.com/buildpacks/rfcs/pull/145 ?)

**Comment by cmoulliard** [comment]
> Hooks

That should b great to have a sample about what a hooked project will look like (+ Dockerfile, Hook TOML, ...)

1. Non hooked
```
builders
└── maven-jvm
    └── builder.toml
 
buildpacks/maven
├── bin
│   ├── build
│   └──detect
└── buildpack.toml
```
2. Hooked project
???

**Comment by natalieparellano** [comment]
Completed as part of #709 (see [comment](https://github.com/buildpacks/lifecycle/issues/709#issuecomment-1101448746)).
