### ISSUE TITLE
Cache Go modules in our GitHub worflows

### ISSUE THREAD

**Issue by ShubhamPalriwala** [buildpacks/lifecycle#718]
### Description
Our GitHub actions usually take 13-15 minutes on average to build and perform the tests. We can speed this process up as most of our dependencies remain the same.

### Proposed solution
GitHub actions can cache modules that are repeatedly used. By using the [cache action by GitHub](https://github.com/actions/cache), we can speed up our workflows

**Comment by ShubhamPalriwala** [comment]
Would like to create a small PR for this if we are going ahead with this issue
@natalieparellano

**Comment by natalieparellano** [comment]
That would be awesome! Thank you, @ShubhamPalriwala !

**Comment by natalieparellano** [comment]
Apologies for the slow response - maybe let's table this for now, we could revisit it later if we need to. Thank you for taking the time to test this out!
