### ISSUE TITLE
Support Syft SBoM format

### ISSUE THREAD

**Issue by sclevine** [buildpacks/lifecycle#755]
[Syft](https://github.com/anchore/syft) and [Grype](https://github.com/anchore/syft) are image scanning utilities that follow our design goal of generating SBoMs for images that can be used for continuous identification of vulnerabilities without rescanning images. As far as I'm aware, they are the only OSS scanning tools that follow this pattern so far.

While both Syft and Grype intend to [support CycloneDX](https://github.com/anchore/grype/issues/481) input/output longer-term, Grype currently requires Syft's [well-defined JSON format](https://github.com/anchore/syft/tree/main/schema/json) to match vulnerabilities.

Given that accepted RFC0095 [states](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md#how-it-works):

> Addition of any new SBOM formats that do not require a merged SBOM need not require an RFC in the future as it would ideally just be a minor change in the lifecycle and spec to update the media type mappings to the file extension.

I would like to recommend that we add the media type for Syft SBoM to the lifecycle to support vulnerability matching.

I am unsure what the appropriate media type to use for Syft SBoM would be (E.g., `application/vnd.syft+json`).

**Comment by samj1912** [comment]
This has been implemented and can be closed.
