### ISSUE TITLE
Incorrect location in comment describing resulting SBOM file location

### ISSUE THREAD

**Issue by robdimsdale** [buildpacks/lifecycle#766]
### Description

[This comment](https://github.com/buildpacks/lifecycle/blob/main/builder.go#L143-L150) suggests that the resulting location for the layer sbom file is: `/layers/sbom/buildpack.id/launch/layer/sbom.<format>.json` but the code below the comment actually copies the sbom to: `/layers/sbom/launch/buildpack.id/layer/sbom.<format>.json` - i.e. the `buildpack.id` and `launch` directories are switched.

### Proposed solution

We are happy to submit a PR to fix the comment, assuming that the code is behaving as intended. We wanted to validate that the comment was wrong (and the code correct) before submitting a PR.

cc @fg-j

**Comment by natalieparellano** [comment]
@robdimsdale thanks for creating this issue! You are correct about the comment being incorrect :)

**Comment by robdimsdale** [comment]
@natalieparellano great, thank you for clarifying. Do you want a PR to update the comment? We could remove it entirely but we found the comment helpful when learning how the lifecycle copies SBOM files, so we'd prefer to fix the comment.

**Comment by natalieparellano** [comment]
@robdimsdale a PR would be much appreciated!

**Comment by natalieparellano** [comment]
@robdimsdale I was able to take care of this. Thanks again for reporting this!

**Comment by robdimsdale** [comment]
Thanks! Sorry I didn't get to the PR before you did.
