### ISSUE TITLE
Question: Why is creator lifecycle trying to switch user context?

### ISSUE THREAD

**Issue by ajdergute** [buildpacks/lifecycle#776]
### Description

We're trying to run creator lifecycle in our GitLab CI pipeline. To do so we're running this docker image:
https://hub.docker.com/layers/paketobuildpacks/builder/latest/images/sha256-988d9d956b62d18a828ea9deab5586d5a307becae23c72c76746c8307048d56f?context=explore

The used GitLab k8s executor is running unprivileged containers with some mounted volumes. It's definitely not user 1000.
When running /cnb/buildpacks/creator it's failing with:

failed to exec as user 1234:1234 operation not permitted

Afaik setresguid and setresuid is called, see:

https://github.com/buildpacks/lifecycle/blob/51280df55b9e5c8c5ecf9bd95767a04bac9765ab/cmd/lifecycle/creator.go#L147

I tried running creator with several combinations of gid, uid, foo-dir flags without success.
I set all dir-flags to directories where our user has write permissions in 

Question: Why do we need to to switch/ensure a specific user?

**Comment by natalieparellano** [comment]
Hi @ajdergute - thanks for your question. The `priv` code that is highlighted exists for when the creator binary is run as root (for example, when connecting to a docker daemon). The creator does what it needs to as root and then drops privileges to whatever is provided with the `-uid` and -`gid` flags, falling back to `CNB_USER_ID` and `CNB_GROUP_ID` in the builder image. For `paketobuildpacks/builder:base`, this should be 1000:1000, so I am curious where the 1234:1234 is coming from - are you passing that in somehow?

**Comment by ajdergute** [comment]
Hi @natalieparellano, thanks for your answer.
Yes 1234 is just a placeholder for the user I'm running my docker image. So let's assume I'm running the image with a user 1234.

As I'm running this image as a normal user and NOT root, I assume dropping privileges is not needed. Right?

It seems to me that this part tries to set uid to 1234, which is the uid the image is actually running with.

**Comment by ajdergute** [comment]
Hey there i've some updates with more informations on this. I forgot to check the group my container is running with. I assumed it's the same as the user, but it's the root group (0).

So with
```
/cnb/lifecycle/creator -app . -tag ${TAG} -gid 0 -uid 1234 ${CI_PROJECT_NAME}
```
i'm able to run the lifecycle till phase _exporting_.
Thank's for the explanations.
