### ISSUE TITLE
 Open Use SOURCE_DATE_EPOCH to configure image create time

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#809]
### Description
See related RFC: https://github.com/buildpacks/rfcs/pull/204 (blocking)

See related imgutil PR: https://github.com/buildpacks/imgutil/pull/137

There is currently an open question around how this should be implemented (in imgutil or the lifecycle). Depending on what is decided, this might not require any further work.

**Comment by natalieparellano** [comment]
There seems to be general agreement that the "alternate" approach mentioned in the RFC is preferred:

> have the `exporter` read the variable and provide it via a new `SetCreatedAt()` method on the `imgutil.Image` interface

There is still some discussion around whether the env var should be `SOURCE_DATE_EPOCH` or `CNB_SOURCE_DATE_EPOCH`, but I think we could unblock this for now because it would be very easy to change it later.

**Comment by natalieparellano** [comment]
Resolved by #823

**Comment by thedevelopnik** [comment]
Thank you so much! This is a long-awaited feature and I am so grateful it landed!
