### ISSUE TITLE
Refactor detector_test.go to be less painful

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/lifecycle#866]
### Description
Here's an example test setup, for the simplest possible case:
```
					bpA1 := testmock.NewMockBuildModule(mockCtrl)
					dirStore.EXPECT().Lookup(buildpack.KindBuildpack, "A", "v1").Return(bpA1, nil)
					bpA1.EXPECT().ConfigFile().Return(&buildpack.Descriptor{API: "0.3", Buildpack: buildpack.Info{ID: "A", Version: "v1"}})
					bpA1.EXPECT().Detect(gomock.Any(), gomock.Any())
```
This is pretty hard to make sense of.

### Additional context
Why it's like this:
* Previously, we didn't have a `DirStore` or a `BuildModule` or a `Resolver` - so the detect tests were essentially integration tests, but without a container. We had to provide a real buildpacks directory with real /bin/build executables, and we controlled the behavior of those binaries through hacky means (we still do this in buildpack/detect_test.go and buildpack/build_test.go). This was cumbersome. 

### Proposed solution
* We could make the tests easier to read by making a service that wraps the calls to `DirStore.Lookup()` and `BuildModule.Detect()`. 
* We could potentially record if we are calling detect for an order or for a single group element.
* ..other things not thought of yet

**Comment by desenna** [comment]
@natalieparellano Looks like this is done per above PR and Dockerfiles phase 2 PR, right?

**Comment by natalieparellano** [comment]
Ah, you are correct @desenna - I'll close this issue.
