### ISSUE TITLE
[RFC #0093] Remove Shell-Specific Logic - Buildpack API

### ISSUE THREAD

**Issue by mboldt** [buildpacks/lifecycle#870]
This issue has been split from #693 to capture the Buildpack API side of [RFC #0093 Remove Shell Processes](https://github.com/buildpacks/rfcs/blob/main/text/0093-remove-shell-processes.md). See https://github.com/buildpacks/spec/pull/305 for details on the Buildpack API spec changes to be implemented.

**Comment by natalieparellano** [comment]
Resolved by #889
