### ISSUE TITLE
Warning when attempting to delete cache image breaks formating

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#880]
# Summary

When an error occurs in attempting to delete the previous cache image, the formatting of the output breaks.

ie:

```
Reusing cache layer 'samples/java-maven:jdk'
Adding cache layer 'samples/java-maven:maven_m2'
Unable to delete previous cache image: DELETE https://index.docker.io/v2/jar013/cacheflag/manifests/sha256:6382cb6220d4858aacbe8985373110dd4f6b6d15d2324d6fc14024061e2c6630: UNSUPPORTED: The operation is unsupported.Successfully built image index.docker.io/jar013/cacheflag:0918
```

Notice that the message "Successfully built image index.docker.io/jar013/cacheflag:0918" is not in a new line.

Expected:

```
Reusing cache layer 'samples/java-maven:jdk'
Adding cache layer 'samples/java-maven:maven_m2'
Warning: Unable to delete previous cache image: DELETE https://index.docker.io/v2/jar013/cacheflag/manifests/sha256:6382cb6220d4858aacbe8985373110dd4f6b6d15d2324d6fc14024061e2c6630: UNSUPPORTED: The operation is unsupported.
Successfully built image index.docker.io/jar013/cacheflag:0918
```

# Possible Solution

The area printing the error is here:
https://github.com/buildpacks/lifecycle/blob/746b0978f70ee1155381a6dcfa6190d9592aff92/cache/image_cache.go#L117-L119

1. This appears to be the [only area where `fmt.Printf` is used](https://github.com/buildpacks/lifecycle/search?l=Go&q=Printf). I would expect this line to be using the [provided logger](https://github.com/buildpacks/lifecycle/blob/746b0978f70ee1155381a6dcfa6190d9592aff92/exporter.go#L38).
2. The cmd/logger already handles missing new line characters. https://github.com/buildpacks/lifecycle/blob/746b0978f70ee1155381a6dcfa6190d9592aff92/cmd/logs.go#L81-L87
3. It would be idea to be annotated as a "Warning".

**Comment by harshalmittal4** [comment]
Hi @jromero @natalieparellano , I am learning about buildpacks and Go. I would like to pick this up

**Comment by harshalmittal4** [comment]
Hi @jromero @natalieparellano , I am learning about buildpacks and Go. I would like to pick this up

**Comment by jjbustamante** [comment]
Hi @harshalmittal4 That's great! I just assigned that one to you! Let us know if you need any help

**Comment by jjbustamante** [comment]
Hi @harshalmittal4 

Checking your comments and the proposed solution by Javier, here are my thoughts. I will use this Class diagram:

- The `ImageCache` should have an internal reference to `log.Logger` "github.com/buildpacks/lifecycle/log", I think it must be added into the constructor methods exposed.
- We need to find who is responsible for creating the instance of the `ImageCache`, it looks like  `DefaultCacheHandler` and  also this class should be handling some logger instance and pass it through to `ImageCache` 
- At the end, the default logger instance `cmd.DefaultLogger` will be the one you end up passing through to every class, but that will be the responsible of the caller. 

``` mermaid
classDiagram

class Logger
class DefaultCacheHandler
class ImageCache {
   NewImageCache(origImage , newImage imgutil.Image, logger log.Logger) ImageCache
   NewImageCacheFromName(name string, keychain authn.Keychain, logger log.Logger) ImageCache
}

ImageCache o-- Logger
ImageCache <.. DefaultCacheHandler : creates
```

Regarding on how to test it, `log.Logger` is an interface and we have a `DefaultLogger` implementation of it, maybe you can create some `TestLogger` wrapper like this:

``` mermaid
classDiagram

class Logger
class TestLogger
class MockLogger
TestLogger --|> Logger
MockLogger --|> Logger
```
Save if the warning message was called, and then Assert during your test, also, maybe a Mock logger can be created to assert that the method was actually called.

I hope this can help you, or maybe @natalieparellano has some other thoughts :)

**Comment by harshalmittal4** [comment]
Thanks @jjbustamante @natalieparellano ,  I will use this approach and try creating a TestLogger. I've not written tests in Go till now, so may take some time. I will send the PR for review when ready

**Comment by harshalmittal4** [comment]
Hi @natalieparellano , @jjbustamante , 
I had some health issues due to which I couldn't attend to this earlier. I'm feeling better now and raised https://github.com/buildpacks/lifecycle/pull/1012. I have a doubt regarding how to invoke the logger.Warnf(), may you please review it.

**Comment by natalieparellano** [comment]
@harshalmittal4 really glad to hear you're feeling better :) will take a look...
