### ISSUE TITLE
Launcher fails to find default process when process type contains `.`

### ISSUE THREAD

**Issue by fg-j** [buildpacks/lifecycle#895]
### Summary

This was initially uncovered in https://github.com/paketo-buildpacks/dotnet-publish/pull/356, where the Paketo buildpacks use .NET Core project names as process types. Some of these look like `Steeltoe.Demo`. It's common for .NET project names to contain `.`. The buildpacks spec [states](https://github.com/buildpacks/spec/blob/main/buildpack.md#launchtoml-toml) that `.` is a valid character in a process type name. However, when process types contain this character, the launcher fails to identify the default process at app launch time. The launcher fails with the error
```
ERROR: failed to launch: determine start command: when there is no default process a command is required
```
---

##### Steps

Follow the reproduction steps in the README.md for this minimal sample buildpack + sample app: https://github.com/fg-j/explorations/tree/main/launcher-bug

##### Current behavior

```
docker run --rm -it sample-app
ERROR: failed to launch: determine start command: when there is no default process a command is required
```

##### Expected

```
docker run --rm -it sample-app
Default entrypoint process
```

---

##### lifecycle version

```
pack builder inspect cnbs/sample-builder:bionic
Inspecting builder: cnbs/sample-builder:bionic

REMOTE:

Created By:
  Name: Pack CLI
  Version: 0.27.0+git-f4f5be1.build-3382

Trusted: No

Stack:
  ID: io.buildpacks.samples.stacks.bionic

Lifecycle:
  Version: 0.14.1
  Buildpack APIs:
    Deprecated: (none)
    Supported: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8
  Platform APIs:
    Deprecated: (none)
    Supported: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9

Run Images:
  cnbs/sample-stack-run:bionic
```

##### platform version(s)

```
pack report
Pack:
  Version:  0.27.0+git-f4f5be1.build-3382
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.14.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9
```

**Comment by natalieparellano** [comment]
Thanks for reporting this @fg-j - we'll look into it.

**Comment by jjbustamante** [comment]
After reproducing the error with the steps provided by @fg-j (Thanks a lot for that! ❤️ ) here is my findings.

The error is generated [here](https://github.com/buildpacks/lifecycle/blob/main/cmd/launcher/cli/launcher.go#L76). Based on the `os.Args[0]` value we are trying to determine the process type. 

```
os.Args[0] = '/cnb/process/default.process'
Base = 'default.process'
Ext = '.process'
```
Finally the line of code:

``` golang
process := strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0]))
```
Removes `.process` from `default.process` and that breaks the evaluation. According to the Launcher [Spec](https://github.com/buildpacks/spec/blob/main/platform.md#launcher)

`If the final path element in $0, matches the type of any buildpack-provided process type...` it seems actually to a spec bug to me in the launcher, right? @natalieparellano

**Comment by samj1912** [comment]
@jjbustamante I'm guessing extensions come into play for windows. `.exe`?

**Comment by jjbustamante** [comment]
That's a good hint @samj1912 ! it makes sense. Maybe a good way to validate could be to move the extension when the OS is window
