### ISSUE TITLE
/cnb/lifecycle/creator with SOURCE_DATE_EPOCH env var not working

### ISSUE THREAD

**Issue by uqix** [buildpacks/lifecycle#943]
### Summary

According to the spec here https://github.com/buildpacks/spec/blob/main/platform.md#exporter, I try to pass `SOURCE_DATE_EPOCH ` env var to `/cnb/lifecycle/creator`:

```sh
SOURCE_DATE_EPOCH=$(date -d $CI_COMMIT_TIMESTAMP +%s) /cnb/lifecycle/creator \
  -app=$module_dir \
  -cache-image=$cache_image \
  -skip-restore=$skip_restore \
  -run-image=$run_image \
  $extra_creator_flags \
  $image
```

but the creation date of the resulting image is still 01/01/1980.

---

##### Steps

1. `SOURCE_DATE_EPOCH=... /cnb/lifecycle/creator ...`

##### Current behavior

Image creation date = 01/01/1980

##### Expected

Image creation date = <SOURCE_DATE_EPOCH>

---

##### lifecycle version

paketobuildpacks/builder:0.3.45-base

https://github.com/paketo-buildpacks/base-builder/releases/tag/v0.3.45

```
Lifecycle:
  Version: 0.14.1
  Buildpack APIs:
    Deprecated: (none)
    Supported: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8
  Platform APIs:
    Deprecated: (none)
    Supported: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9
```

##### platform version(s)

0.9

**Comment by jjbustamante** [comment]
@uqix Did you try setting the environment variable `CNB_PLATFORM_API` to 0.9?

**Comment by uqix** [comment]
@jjbustamante Following your tips fixed the image creation date issue, but the build output files' timestamps are still zero:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/10142314/198216417-f615327c-bc28-4858-af61-c1ee37fa33ef.png">

**Comment by samj1912** [comment]
@uqix that is expected. The SOURCE_DATE_EPOCH only applies to the OCI config/metadata files.

**Comment by uqix** [comment]
@samj1912 thanks, so any tip for this [issue](https://github.com/paketo-buildpacks/nginx/issues/447)?

**Comment by natalieparellano** [comment]
In theory we could in the future allow buildpacks to set metadata on a per-layer basis to have the lifecycle omit zeroing the timestamps for particular layers. But this would require an RFC...

**Comment by uqix** [comment]
I see, I misunderstood the `SOURCE_DATE_EPOCH` at the very first, close this issue now.
