### ISSUE TITLE
RFC for SBOM describing lifecycle / launcher

### ISSUE THREAD

**Issue by omocquais-p** [buildpacks/lifecycle#958]
### Description
[]
[https://github.com/buildpacks/rfcs/blob/main/text/0112-launcher-sbom.md](https://github.com/buildpacks/rfcs/blob/main/text/0112-launcher-sbom.md)

**Comment by natalieparellano** [comment]
Resolved by https://github.com/buildpacks/lifecycle/pull/944 and https://github.com/buildpacks/lifecycle/pull/963
