### ISSUE TITLE
Include full lifecycle log output on failed builds to improve debugging

### ISSUE THREAD

**Issue by mgibson1121** [buildpacks/lifecycle#967]
### Description

This feature request is in reference to a problem kpack users encounter when trying to debug problems using lifecycle log output.  In the event that no buildpacks detect as part of a kpack build, the full lifecycle logs are not printed, which makes it difficult to troubleshoot the root of the problem.    

### Proposed solution
Print full lifecycle logs. In order to avoid overwhelming the user, perhaps this verbose log output could only be surfaced on failed detection for the detect phase.

### Describe alternatives you've considered

The kpack project had a couple of ideas such as attempting detection again or on a build failure try again with verbose logging. Due to how kpack builds are usually not user triggered (rather automatically triggered to match the user's desired state), it is difficult/clunky to mimic the `pack` CLI's verbose flag command. It would instead be preferable to address this at the lifecycle level.

**Comment by natalieparellano** [comment]
This was discussed previously in https://github.com/buildpacks/lifecycle/issues/283#issuecomment-636145655

Options discussed included:
* Printing output as info-level when a buildpack exits with error code not 0 or 100 (indicating an error in ./bin/detect vs buildpack opted out of the build)
* Printing output as info-level when detect fails (all buildpacks failed to detect)

At the time, we only implemented the first part as it was easier and we were awaiting more feedback about detect logs. Given that such feedback has arrived and the latter is still possible, we should go ahead and do this.
