### ISSUE TITLE
[RFC 0115] Add `-previous-image` to rebase

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/lifecycle#983]
### Description
Add `-previous-image` as an optional input to rebase command.

### Proposed solution
Add `-previous-image` as an optional input to rebase command. When `-previous-image` is provided, use the provided image reference for the previous image and _require_ a `-tag` input. The `-previous-image` will _not_ be a push target for a successful rebase.

More details can be found in the **[RFC](https://github.com/buildpacks/rfcs/pull/262).**

### Additional context
RFC: https://github.com/buildpacks/rfcs/pull/262

**Comment by jabrown85** [comment]
Question for you @natalieparellano - could/should we tie this to a platform version? Since this is a new optional argument, I suppose we don't have to.

**Comment by joeybrown-sf** [comment]
[RFC](https://github.com/buildpacks/rfcs/blob/main/text/0115-rebase-immutable-image-ref.md)
